### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by captainwasabi** [micwallace/wallacepos#1]
[Wed Apr 29 21:27:12 2015] [error] [client 192.168.2.238] PHP Parse error:  syntax error, unexpected '[' in /usr/share/wallacepos-master/library/wpos/models/DbUpdater.php on line 105

Running ubuntu 12.04 in a VM (but I can run whatever you recommend)

Also, how do I install mod_wstunnel.  I installed mod_proxy and that let apache start after adding the lines to /etc/apache2/apache.conf

Thanks!

**Comment by micwallace** [comment]
Hi this error is because you are not using the right php version.
You need at least php 5.4 which has function array dereferencing.

Will update the readme tonight with proper prerequisites. Apologies for it being pretty crap at the moment!

**Comment by captainwasabi** [comment]
Just for reference this is how to upgrade 12.04 and it's best to do it first because it can replace modified config files: http://www.pixelite.co.nz/article/upgrading-php-54-ubuntu-1204-lts-support-drupal-8/
