### ISSUE TITLE
There was an error connecting to the server Pop Up

### ISSUE THREAD

**Issue by jonhellinga** [micwallace/wallacepos#10]
I've checked my mysql settings over and over and am not sure what would cause this issue.  I see the login screen for admin and am able to type in credentials, but during "initializing" I get this pop up error.

**Comment by micwallace** [comment]
It's most likely an issue with the apache rewrite.
Have you installed mod_rewrite?
Please send through your virtual host config & check /var/log/apache2/error.log for any details

**Comment by micwallace** [comment]
I'll enhance the install script to check for dependencies in the next version.
