### ISSUE TITLE
When I try to install I get php code instead installer

### ISSUE THREAD

**Issue by ravindug** [micwallace/wallacepos#101]
When I try to install I get php code instead installer,
I cloned the repo and installed with composer and install socket.io and enabled everything in apache config as mentioned.

you can check the url here : https://siyambalapos.ml/installer/

**Comment by micwallace** [comment]
Can you view any php page? Chances are mod-php is missing from your apache installation. Please resubmit the issue using the issues template is problems persist. Simply not enough info here to investigate further.
