### ISSUE TITLE
When I try to install I get php code instead installer 2

### ISSUE THREAD

**Issue by ravindug** [micwallace/wallacepos#104]
[provide general introduction to the issue logging and why it is relevant to this repository]

## Context

When I go to installer it just output php code...https://siyambalapos.ml/installer/

but login page is working ...https://siyambalapos.ml/

and I installed  all the packages and composer install and update too I don't  know why I can't get installer working

**Comment by micwallace** [comment]
This error has nothing to do with this application. You obviously don't have your webserver configured correctly and have not provided enough info here to investigate. If you don't know how to configure a web server please seek professional support.

**Comment by ravindug** [comment]
what kind of info you need to investigate? I followed all the steps enabled Apache modules and don't know why it just shows  php ĉode only at installer page

**Comment by micwallace** [comment]
No, don't be so rude to think I would spend my time to troubleshoot an issue that has nothing to do with the application. Use google or hire an expert!

**Comment by ravindug** [comment]
Extremely sorry if you got offended, never meant to be rude and I apologize, just got annoyed with this error tried many thing but nothing worked out for me , thank you again for your time again and beg you pardon again.

**Comment by micwallace** [comment]
No worries, I just don't like that people get a free product and then expect free support for it too.
Github is a community for open-source contribution, not a support forum. You get out of it what you put back in. Plus if you want to use this product in production you'll have to learn to investigate these things yourself, or hire someone else to do it.

It literally took a single Google search to find some possible solutions:
http://lmgtfy.com/?q=apache+php+code+not+parsed

https://stackoverflow.com/questions/9305680/apache-virtual-host-not-parsing-php
