### ISSUE TITLE
Sub Directoy

### ISSUE THREAD

**Issue by 9foxlabs** [micwallace/wallacepos#106]
[provide general introduction to the issue logging and why it is relevant to this repository]

**Added Wallace POS as a Sub directory and now it will not connect to api/  ...   api/hello**

[provide more detailed introduction to the issue itself and why it is relevant]

**I can hit socket.io but will not hit api/....    api/hello**

**Comment by ravindug** [comment]
not clear what you are saying but I think you must configure virtual host properly?

**Comment by micwallace** [comment]
There are some absolute urls used in places on the client side. You'd need to modify the Javascript (/assets/js/wpos/core.js) to use another base path. Better to use a subdomain with that directory as the root.

**Comment by 9foxlabs** [comment]
urls in core.js that are similar to this were all changed but it wont get past "/api/hello" for some reason. it hits the socket but that is it?

Any Ideas? would like to Not have to use a Sub domain if possible

Do you think @ravindug  is on to something in his comment above?

Thank you

function checkOnlineStatus() {
        try {
            var res = $.ajax({
            timeout : 3000,
            url     : "/newpos/api/hello",
            type    : "GET",
            cache   : false,
            dataType: "text",
            async   : false
            }).status;
            online = res == "200";
        } catch (ex){
            online = false;
        }
        return online;
---------------------------------------------------------
// GLOBAL COM FUNCTIONS
    this.sendJsonData = function (action, data) {
        // send request to server
        try {
        var response = $.ajax({
            url     : "/newpos/api/"+action,

**Comment by micwallace** [comment]
You might need to change the rewrite rule in your virtual host config?

**Comment by 9foxlabs** [comment]
Can you give me a hint please?

**Comment by micwallace** [comment]
Change RewriteBase in /api/.htaccess? If that doesn't work you need to troubleshoot further.

**Comment by 9foxlabs** [comment]
do you see anything in here that you looks like it should be changed?

Options +FollowSymlinks
Options -MultiViews
RewriteEngine on
RewriteBase /customerapi/
RewriteCond %{REQUEST_URI} !customerapi.php
RewriteRule ^(.*)$ customerapi.php?a=$1 [L,NS,QSA]

**Comment by micwallace** [comment]
Geez take a hint! RewriteBase; include your subdirectory.

**Comment by 9foxlabs** [comment]
i'm new to this. thank you for being understanding

**Comment by 9foxlabs** [comment]
here is the error...in the pop up window when first hitting the url

 "There was an error connecting to the webserver & files needed to run offline are not present :(

I'll let you know if changing the RewriteBase works.

thank you
