### ISSUE TITLE
installing wallacePOS on ubuntu 16 facing issues 1.)unable to get green check mark on Node.js Socket.IO library installed in /installer even after installing socket.io@2.0.3  and 2.)Folder Permissions: App Root / must be writable >> does it mean the /var/www/html should be owned by apache2, it is already owned by  www-data 3:)And red check mark on Apache Configuration: HTTPS Active

### ISSUE THREAD

**Issue by nishantpradhan** [micwallace/wallacepos#107]
[provide general introduction to the issue logging and why it is relevant to this repository]

## Context

[provide more detailed introduction to the issue itself and why it is relevant]

## Process

[ordered list the process to finding and recreating the issue, example below]

1. User goes to delete a dataset (to save space or whatever)
2. User gets popup modal warning
3. User deletes and it's lost forever

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you you currently experience from this process, and thereby explain the bug]

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

* Modal tells the user what dataset is being deleted, like “You are about to delete this dataset: car_crashes_2014.”
* A temporary "Trashcan" where you can recover a just deleted dataset if you mess up (maybe it's only good for a few hours, and then it cleans the cache assuming you made the right decision).

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by micwallace** [comment]
This issue is not valid. Write a proper description, include virtual host configurations, Don't just put everything in the title. Fill out the issue template completely or remove the sections that do no apply.
