### ISSUE TITLE
Tax data could no be retrived:

### ISSUE THREAD

**Issue by vegapaul** [micwallace/wallacepos#109]
After a good install: first login I receive this message.

## Context
![screen shot 2017-07-19 at 9 07 42 pm](https://user-images.githubusercontent.com/18123313/28396031-aeb2097e-6cc6-11e7-8bdf-384002573f9d.png)

**Comment by micwallace** [comment]
This error means that installation was not performed or not successful. Please verify that the database tables are installed.
