### ISSUE TITLE
There was an error connection to the server: OK

### ISSUE THREAD

**Issue by silentbob90** [micwallace/wallacepos#11]
Ive been trying to install but keep getting this error on admin login
There was an error connection to the server: OK

**Comment by micwallace** [comment]
I'd need some further information.
Maybe you will find an error in /var/log/apache/error.log?
Or check firebug/chrome dev tools?
And confirm that you have installed the database properly.

**Comment by micwallace** [comment]
Hey mate,

I just had a look at the link you sent me.

You'll need install in the document root directory unless you want to 
edit the code:
ie. http://yourdomain.com/admin

In a future version, the application root will be a editable config 
value but for now it is set in several places in the code.
Until then, if you need to have something else on the main domain, use a 
subdomain instead:
http://pos.yourdomain.com/admin

**Comment by silentbob90** [comment]
Perfect that sorted it thanks.
Great work by the way!

**Comment by micwallace** [comment]
Good to hear & no worries.
Keep an eye out for a new version later in the year with better 
internationalisation & tax support.
