### ISSUE TITLE
Apache Proxy Error : AH01114: HTTP: failed to make connection to backend: localhost

### ISSUE THREAD

**Issue by Dark-Rabbit** [micwallace/wallacepos#110]
Hi All,

So I'm new to all off this, here goes.

## Context

I have set up Wallacepos and think its great however every now and then the admin console seems to go into this loop when the circle pointer just goes round and round. I thought it might be a sql issue but cant find any issues in the logs, i tuned mysql and gave the server some more resources.

but alas the problem continued, i eventually found some issues in the Apache logs. 

## Process

When the admin is navigating the Dashboard and Inventory system hangs

## Expected result

Tables and requested information should load 

## Current result

system appears to get stuck in a loop

## Possible Fix

cant determine this yet, although I did add the following to my Apache config for the site to try mitigate it 
ProxyPass        /socket.io http://localhost:8080/socket.io/ retry=0 timeout=5

## `name of issue` screenshot
Errors from my apache logs:

[Mon Jul 24 07:53:51.463833 2017] [proxy_http:error] [pid 22016] [client ###IP ADDRESS###:28219] AH01114: HTTP: failed to make connection to backend: localhost, referer: https://DOMAIN/
[Mon Jul 24 07:53:57.395713 2017] [proxy:error] [pid 22012] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:8080 (localhost) failed
[Mon Jul 24 07:53:57.395892 2017] [proxy:error] [pid 22012] AH00959: ap_proxy_connect_backend disabling worker for (localhost) for 0s
[Mon Jul 24 07:53:57.395955 2017] [proxy_http:error] [pid 22012] [client ###IP ADDRESS###:28235] AH01114: HTTP: failed to make connection to backend: localhost, referer: https://DOMAIN/

System App Ver:
Ubuntu 16.04
PHP 7.0
Apache2 2.4.18
nodejs 4.2.6
nodejs-dev 4.2.6 

#####

Any help would be greatly appreciated

P.S: I'm not afraid to put in the work but some guidance in the necessary direction always goes a long way.

South Africa, noted you like to ask where we are from

**Comment by micwallace** [comment]
Appreciate the detailed report. I think we are dealing with a few errors here. The proxy error that your getting should not cause the dashboard to hang, although it will stop realtime updates from working. I think this is a Javascript error. Can you please look in the javascript console and post any errors received here?

Note that you should have your virtual host configured with a domain name and SSL certificate, even if the certificate is just self-signed.

**Comment by Dark-Rabbit** [comment]
Hi There,

wow thanks for the quick reply, Doesn't seem to be freezing up right at this  point, but as you mention the "realtime" dose through the following issues in the console,


socket.io-1.4.5.js:1 GET https://pos.XXREDACTEDXXX.co.za/socket.io/?EIO=3&transport=polling&t=Lrq0EUG 503 (Service Unavailable)
Request.create @ socket.io-1.4.5.js:1
Request @ socket.io-1.4.5.js:1
XHR.request @ socket.io-1.4.5.js:1
XHR.doPoll @ socket.io-1.4.5.js:1
Polling.poll @ socket.io-1.4.5.js:1
Polling.doOpen @ socket.io-1.4.5.js:1
Transport.open @ socket.io-1.4.5.js:1
Socket.open @ socket.io-1.4.5.js:1
Socket @ socket.io-1.4.5.js:1
Socket @ socket.io-1.4.5.js:1
Manager.open.Manager.connect @ socket.io-1.4.5.js:2
Manager @ socket.io-1.4.5.js:2
Manager @ socket.io-1.4.5.js:2
lookup @ socket.io-1.4.5.js:2
WPOSAdmin.startSocket @ wpos.js:549
(anonymous) @ VM337:366
l @ jquery-2.0.3.min.js:4
add @ jquery-2.0.3.min.js:4
ready @ jquery-2.0.3.min.js:4
init @ jquery-2.0.3.min.js:4
x @ jquery-2.0.3.min.js:4
(anonymous) @ VM337:321
globalEval @ jquery-2.0.3.min.js:4
domManip @ jquery-2.0.3.min.js:5
append @ jquery-2.0.3.min.js:5
(anonymous) @ jquery-2.0.3.min.js:5
access @ jquery-2.0.3.min.js:4
html @ jquery-2.0.3.min.js:5
(anonymous) @ wpos.js:115
l @ jquery-2.0.3.min.js:4
fireWith @ jquery-2.0.3.min.js:4
k @ jquery-2.0.3.min.js:6
(anonymous) @ jquery-2.0.3.min.js:6
socket.io-1.4.5.js:1 GET https://pos.XXREDACTEDXXX.co.za/socket.io/?EIO=3&transport=polling&t=Lrq0G7I 503 (Service Unavailable)
Request.create @ socket.io-1.4.5.js:1
Request @ socket.io-1.4.5.js:1
XHR.request @ socket.io-1.4.5.js:1
XHR.doPoll @ socket.io-1.4.5.js:1
Polling.poll @ socket.io-1.4.5.js:1
Polling.doOpen @ socket.io-1.4.5.js:1
Transport.open @ socket.io-1.4.5.js:1
Socket.open @ socket.io-1.4.5.js:1
Socket @ socket.io-1.4.5.js:1
Socket @ socket.io-1.4.5.js:1
Manager.open.Manager.connect @ socket.io-1.4.5.js:2
(anonymous) @ socket.io-1.4.5.js:3

Thanks for the advice, i have an SSL deployed and I'm enforcing HTTPS, i will keep the console open during the day to try and capture the error when it freezes up.

Cheers,

**Comment by micwallace** [comment]
Ok sounds like a plan!

In the meantime here are some steps you can take to debug node.js:
1. Make sure node is running with: `ps aux | grep node`
    It should display a single line with the node.js process.
2. Run node manually in debug mode to see what it's receiving: `DEBUG=* node api/server.js`
    (run from application root directory. you will have to stop/kill the current node.js process first)
3. Post your virtual host config, I'll see if I can spot any issues.

**Comment by Dark-Rabbit** [comment]
Hi There,

okay so first off face palm, no Node was running now it is and the errors in the Apache logs seem to have stopped, I truncated the error's log since i started the node in debug mode and redirected STD and STDERR to a log file, if it hangs again I'll grab the logs and also monitor the Apache logs.

Here is my Config for Apache VH:

<VirtualHost pos.##REDACTED###.za:443>
     DocumentRoot /REDACTED-DIR###/
     ServerName pos.##REDACTED###.za

     ErrorLog ${APACHE_LOG_DIR}/pos-error.log
     CustomLog ${APACHE_LOG_DIR}/pos-access.log combined

     SSLEngine on
         SSLCipherSuite !ADH:!DSS:!RC4:HIGH:+3DES:+RC4
         SSLProtocol all -SSLv2 -SSLv3
         SSLCertificateFile /##REDACTED-DIR###/pos.##REDACTED###.za/fullchain.pem
         SSLCertificateKeyFile /##REDACTED-DIR###/pos.##REDACTED###.za/privkey.pem

     <Directory /##REDACTED-DIR###>
        AllowOverride all
     </Directory>

     # WSPROXY CONF
     ProxyRequests Off
     ProxyPreserveHost On
     <Proxy pos.##REDACTED###.za>
             Order deny,allow
             Allow from all
     </Proxy>
     RewriteEngine On
     RewriteCond %{HTTP:Connection} Upgrade [NC]
     RewriteRule /(.*) ws://localhost:8080/$1 [P,L]
     ProxyPass        /socket.io http://localhost:8080/socket.io/ retry=0 timeout=5
     ProxyPassReverse /socket.io http://localhost:8080/socket.io/
     <Location /socket.io>
             Order allow,deny
             Allow from all
     </Location>
</VirtualHost>


Massive thanks for the assist on this.

**Comment by Dark-Rabbit** [comment]
I would like to update this and close it.

If you experiencing issues in your Apache logs with : 

**AH01114: HTTP: failed to make connection to backend: localhost**

1. Make sure node is running with: "ps aux | grep node"
It should display a single line with the node.js process.

This was my issue with the errors,

Also my Admin console seems to be fine now, probably a combo of system issues and mysql. 

Cheers to @micwallace for the assist.

**Comment by tejastank** [comment]
I had resolved: https://stackoverflow.com/a/58111190/1635700
