### ISSUE TITLE
Nginx Support

### ISSUE THREAD

**Issue by digitalwordings** [micwallace/wallacepos#112]
is it possible to add nginx config file? i am using ubuntu and nginx

**Comment by digitalwordings** [comment]
i am using serverpilot nginx as reverse proxy to apache, apache in php-fpm, i configured all but not mod_php, will it work on php-fpm

**Comment by micwallace** [comment]
It will work with nginx as a proxy, I'm using it in a similar way. You just need to make sure websocket requests are also proxied. Here's an example:
```
location    / {
    proxy_pass  http://{{ .APP }};
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  } 
```
The key directives you'll need to add to your config are:
```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```

I haven't tried it php-fpm but it should work fine.
