### ISSUE TITLE
WallacePOS

### ISSUE THREAD

**Issue by Iwan2323** [micwallace/wallacepos#114]
Hello Everybody, my is Iwan, im from Indonesia, i try to install Wallacepos, but i have trouble when installation, i can't click 'Next', can you help me please? for your information, i use OS linux Ubuntu 14.04, thanks all
![bl](https://user-images.githubusercontent.com/29030451/29160187-83cf264e-7ddb-11e7-9bd9-8e493f9faea8.png)

**Comment by micwallace** [comment]
I have already told you via email what the problem is. Your document root is incorrect. 
WallacePOS does not support subfolder installation unless you know what the hell your doing and are able to modify URLs to support it.
Please start over and follow the installation guide!

**Comment by Iwan2323** [comment]
ok mic, im sorry, thanks

Salam,
Iwan Gunawan

2017-08-10 14:58 GMT+07:00 micwallace <notifications@github.com>:

**Comment by Iwan2323** [comment]
Hello Mic,
where is Aplication files?

Salam,
Iwan Gunawan

2017-08-10 15:18 GMT+07:00 Iwan Gunawan <ione232326@gmail.com>:
