### ISSUE TITLE
Unable to print receipt with chinese alt_name

### ISSUE THREAD

**Issue by cyhock** [micwallace/wallacepos#115]
I try to print receipt using Mixed Language, but output only show English name, empty Alternative Name with Chinese Character.

## Context

[provide more detailed introduction to the issue itself and why it is relevant]

## Process

1. I'm using ESC/POS printer, 
2. Connection Method is **Web Print ESCP**, Type is **Raw**, ESCP Receipt Mode is **Text**,
3. Language is **Mixed**
3. Alternate Charset & codepage : both PC864/PC1256 tried, 22,
4. Database data : "alt_name":"\u7389\u7af9\u836f\u6750\u6c64"}

## Expected result

The receipt should show English and Chinese character

## Current result

Receipt only show English name.

## Possible Fix
May I know how to resolve this? thanks.

## `name of issue` screenshot
![image](https://user-images.githubusercontent.com/24717332/29202869-b1e9bf08-7e9e-11e7-91ef-454f3af6653c.png)
Items
![image](https://user-images.githubusercontent.com/24717332/29202681-36591f42-7e9d-11e7-9423-22fd64843bf5.png)
Error from Console

**Comment by micwallace** [comment]
There's only character maps available for Arabic at this stage. However those maps are only used for text mode printing. You should be able to print chinese characters by changing to bitmap receipt mode.
