### ISSUE TITLE
Stuck permissions check page cannot ignore requirements

### ISSUE THREAD

**Issue by pttimothys** [micwallace/wallacepos#117]
i'm very new for this. sorry for disturbing or being silly.
installed in virtualbox , debian 9

already install and configured this about 3 weeks.
i give up.

cannot pass file permission application writeable check
and cannot ignore this file permission check to processing installing.

<img width="602" alt="screen shot 2017-08-29 at 12 10 53 pm" src="https://user-images.githubusercontent.com/31430529/29805466-21f862cc-8cb4-11e7-94ef-fdd6cc8b7f7c.png">

**Comment by micwallace** [comment]
You need to provide more information such as apache error logs & configuration. Could be an issue with session since the installation progress is stored there.

On 29 August 2017 3:18:59 PM AEST, pttimothys <notifications@github.com> wrote:
>
>i'm very new for this. sorry for disturbing or being silly.
>
>already install and configured this about 3 weeks.
>i give up.
>
>cannot pass file permission application writeable check
>and cannot ignore this file permission check to processing installing.
>
>
><img width="602" alt="screen shot 2017-08-29 at 12 10 53 pm"
>src="https://user-images.githubusercontent.com/31430529/29805466-21f862cc-8cb4-11e7-94ef-fdd6cc8b7f7c.png">
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/117

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pttimothys** [comment]
thanks its fixed.

added syntax 

Session_save_path('')

before session_start()
