### ISSUE TITLE
Server Not Found

### ISSUE THREAD

**Issue by adriancamp** [micwallace/wallacepos#12]
Hi installed WallacePOS and everything seems installed ok. However when I go to the admin page I get a popup that says "There was an error connecting to the server: 
Not Found"
![screen shot 2015-09-24 at 2 14 57 pm](https://cloud.githubusercontent.com/assets/14826850/10084098/39494180-62c7-11e5-84d3-a06478c36dda.png)

I will appreciate your help.

Thanks in Advance!

**Comment by micwallace** [comment]
Hi Adrian,

Seems that apache rewrites aren't working. The rewrites specified at /api/.htaccess must be enabled.

Kind regards,
Michael

On 25 September 2015 5:19:27 am AEST, adriancamp <notifications@github.com> wrote:
>Hi installed WallacePOS and everything seems installed ok. However when
>I go to the admin page I get a popup that says "There was an error
>connecting to the server: 
>Not Found"
>![screen shot 2015-09-24 at 2 14 57
>pm](https://cloud.githubusercontent.com/assets/14826850/10084098/39494180-62c7-11e5-84d3-a06478c36dda.png)
>
>I will appreciate your help.
>
>Thanks in Advance!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/12

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
