### ISSUE TITLE
Feature/help for multi client and multi store 

### ISSUE THREAD

**Issue by dipenpatel235** [micwallace/wallacepos#128]
I am looking for help how to archive my goal for multi client with multi store.

For example I have 3 client
ClientA
ClientB
ClientC

Now 
clientA have 3 store with different product in each store

ClientB have 5 store with different product and same as ClientC

So can we do this in current setup or need to modified something..

Thanks

**Comment by jaravena** [comment]
You have 3 installations, one for each client.

**Comment by micwallace** [comment]
Thanks @jaravena that is correct. WallacePOS is not multi-tenant.

**Comment by dipenpatel235** [comment]
My question is if not now then how we can integrate this feature in this ?
Any help ?
