### ISSUE TITLE
Hello, the updates do not work in real time.

### ISSUE THREAD

**Issue by jaravena** [micwallace/wallacepos#129]
Hello, the updates do not work in real time.

Online Devices

Loading...

![captura de pantalla 2018-03-08 a la s 16 53 35](https://user-images.githubusercontent.com/17723913/37173389-3d3252da-22f2-11e8-8409-d6f7ca1a0c9d.png)

**Comment by micwallace** [comment]
This is not reproducible with a working installation. It's an installation problem, check browser console and apache error logs.
