### ISSUE TITLE
Syntax error and page not loading after clicking login

### ISSUE THREAD

**Issue by razmir** [micwallace/wallacepos#13]
Hi Michael,

First of all, thanks a lot for your effort for WallacePos. I'm currently evaluating this.

I'm currently evaluating wallacepos and I have been stuck for a day trying to figure out what is missing. I already follow the guide that you provided for installation but for the first time login at admin page, there is nothing came out. I'm attaching a screenshot of firefox console so that you can take a look at it.

Thanks again

<img width="1278" alt="screen shot 2015-10-17 at 08 45 43" src="https://cloud.githubusercontent.com/assets/15165634/10556042/4d5126e2-74ac-11e5-94d7-ee67884418fa.png">

**Comment by micwallace** [comment]
What data is the request returning (you can view in network tab of firefox dev tools)?

Chances are that you have not set up mod_redirect properly, therefore the api endpoint is not functional.

Cheers,
Michael

On 17 October 2015 11:52:23 am AEDT, razmir <notifications@github.com> wrote:
>Hi Michael,
>
>First of all, thanks a lot for your effort for WallacePos. I'm
>currently evaluating this.
>
>I'm currently evaluating wallacepos and I have been stuck for a day
>trying to figure out what is missing. I already follow the guide that
>you provided for installation but for the first time login at admin
>page, there is nothing came out. I'm attaching a screenshot of firefox
>console so that you can take a look at it.
>
>Thanks again
>
><img width="1278" alt="screen shot 2015-10-17 at 08 45 43"
>src="https://cloud.githubusercontent.com/assets/15165634/10556042/4d5126e2-74ac-11e5-94d7-ee67884418fa.png">
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/13

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by razmir** [comment]
Do you mean apache mod_rewrite instead of mod_redirect?
mod_rewrite is already enable (a2enmod rewrite)
It just end up at POST

<img width="1279" alt="screen shot 2015-10-17 at 11 53 17" src="https://cloud.githubusercontent.com/assets/15165634/10556890/c07ace3e-74c5-11e5-9085-ebc39f1fa750.png">

Thanks

**Comment by micwallace** [comment]
Yep sorry rewrite is what I meant & it seems to be working.
You can probably see what the request is returning, maybe by right clicking the POST request. Otherwise install firebug, it has this info in the network tab.

You should also check the apache error log for any hints.

Cheers,
Michael

On 17 October 2015 2:56:42 pm AEDT, razmir <notifications@github.com> wrote:
>Do you mean apache mod_rewrite instead of mod_redirect?
>mod_rewrite is already enable (a2enmod rewrite)
>It just end up at POST
>
><img width="1279" alt="screen shot 2015-10-17 at 11 53 17"
>src="https://cloud.githubusercontent.com/assets/15165634/10556890/c07ace3e-74c5-11e5-9085-ebc39f1fa750.png">
>
>Thanks
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/13#issuecomment-148883935

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by razmir** [comment]
<?
// WallacePOS database config
$dbConfig = [
    'host'=>'localhost',
    'port'=>'3306',
    'database'=>'pos',
    'user'=>'user',
    'pass'=>'*'
];
{"errorCode":"phpexc","error":"Failed to connect to database.\n","data":""}

Hi Michael

Looks like it failed to connect to database.
Checking back my dbconfig.php file and found out that php tag (?>) at the end is not there.
Looks like it working now, but another error popup after clicking login.

2: fopen(/home/razmir/pos//docs/logswpos_log_15-10-18.txt): failed to open stream: Permission denied /home/razmir/pos//library/wpos/models/Logger.php on line 41

I'm able to get admin page after I refresh the page.

Thanks

**Comment by micwallace** [comment]
Php does not need the closing tag, not sure why that fix is working in your case, old php version perhaps?
Or maybe short tags need to be enabled in php.ini

"Permission denied" is just file permissions error.
apache user needs write permission to docs folder.

One day I'll update the install script to check all these things :-D

Possibly along with the next update which contains lots of internationalization & tax improvements.

Cheers,
Michael

On 18 October 2015 1:08:59 am AEDT, razmir <notifications@github.com> wrote:
><?
>// WallacePOS database config
>$dbConfig = [
>    'host'=>'localhost',
>    'port'=>'3306',
>    'database'=>'pos',
>    'user'=>'user',
>    'pass'=>'*'
>];
>{"errorCode":"phpexc","error":"Failed to connect to
>database.\n","data":""}
>
>Hi Michael
>
>Looks like it failed to connect to database.
>Checking back my dbconfig.php file and found out that php tag (?>) at
>the end is not there.
>Looks like it working now, but another error popup after clicking
>login.
>
>2: fopen(/home/razmir/pos//docs/logswpos_log_15-10-18.txt): failed to
>open stream: Permission denied
>/home/razmir/pos//library/wpos/models/Logger.php on line 41
>
>I'm able to get admin page after I refresh the page.
>
>Thanks
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/13#issuecomment-148918196

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by razmir** [comment]
I'm running 5.6.13-0+deb8u1 currently.
Looks like I forgot to chmod the directory, it's gone now.

Thanks a lot Michael :+1:

**Comment by razmir** [comment]
Update feed could not be connected, 
you will not receive realtime updates!

I already start feed server at settings. Any idea?

Thanks

**Comment by micwallace** [comment]
Try log out and log back in, authorisation is sent to the feed server on login.

Otherwise verify that mod_wsproxy is functioning correctly, check firefox devtools and apache logs for errors.

I'm off to bed now but will get back to you tomorrow if you need further help.

Cheers,
Michael

On 18 October 2015 2:22:32 am AEDT, razmir <notifications@github.com> wrote:
>Update feed could not be connected, 
>you will not receive realtime updates!
>
>I already start feed server at settings. Any idea?
>
>Thanks
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/13#issuecomment-148924332

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by razmir** [comment]
Hi Michael,

I'm getting CORS request failed. Any idea? 
Sorry I have very little experience on this.

<img width="1271" alt="screen shot 2015-10-19 at 14 14 46" src="https://cloud.githubusercontent.com/assets/15165634/10570928/01255556-766c-11e5-8721-94e97b2eac40.png">
<img width="1278" alt="screen shot 2015-10-19 at 14 15 12" src="https://cloud.githubusercontent.com/assets/15165634/10570929/0128c218-766c-11e5-9c12-927360aa7165.png">

Thanks

**Comment by micwallace** [comment]
I think that mod_wsproxy is not working properly but nothing comes to mind using info provided. Can you provide your virtual host config for apache?

On 19 October 2015 4:17:28 pm AEST, razmir <notifications@github.com> wrote:
>Hi Michael,
>
>I'm getting CORS request failed. Any idea? 
>Sorry I have very little experience on this.
>
><img width="1271" alt="screen shot 2015-10-19 at 14 14 46"
>src="https://cloud.githubusercontent.com/assets/15165634/10570928/01255556-766c-11e5-8721-94e97b2eac40.png">
><img width="1278" alt="screen shot 2015-10-19 at 14 15 12"
>src="https://cloud.githubusercontent.com/assets/15165634/10570929/0128c218-766c-11e5-9c12-927360aa7165.png">
>
>Thanks
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/13#issuecomment-149112246

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by razmir** [comment]
Hi Michael,

This is my apache config, I'm running normal HTTP only for now.

<VirtualHost *:80>
         DocumentRoot /home/razmir/pos/
         ServerName pos2.razmir.tk
         ServerAlias pos2.razmir.tk

         ErrorLog ${APACHE_LOG_DIR}/error.log
         CustomLog ${APACHE_LOG_DIR}/access.log combined

         <Directory /home/razmir/pos/>
         Require all granted
         AllowOverride all
         </Directory>

         # WSPROXY CONF
         ProxyRequests Off
         ProxyPreserveHost On
         <Proxy *>
                 Order deny,allow
                 Allow from all
         </Proxy>
         ProxyPass /socket.io/1/websocket/ ws://localhost:8080/socket.io/1/websocket/
         ProxyPassReverse /socket.io/1/websocket/ ws://localhost:8080/socket.io/1/websocket
         ProxyPass /socket.io/ http://localhost:8080/socket.io/
         ProxyPassReverse /socket.io/ http://localhost:8080/socket.io/
         <Location /socket.io>
                 Order allow,deny
                 Allow from all
         </Location>
    </VirtualHost>

Thanks

**Comment by razmir** [comment]
Hi Michael, 

I just notice that in my previous post there's a GET /socket.io/ error. In my root doc, there is no filename socket.io

**Comment by micwallace** [comment]
Yep that's fine, it gets forwarded to node.js service (wstunnel).
You'll need to use https or edit the code so websockets use plain http 
as it's hard coded for now.

**Comment by micwallace** [comment]
PS; If you need to change to http, location is /assets/js/wpos/core.js 
line 994

**Comment by razmir** [comment]
Ok, just enable SSL for on the server. 
Everything looks great accept there's nothing happen when I click process.
Console log attached
<img width="1280" alt="screen shot 2015-10-19 at 20 16 24" src="https://cloud.githubusercontent.com/assets/15165634/10577501/525900c6-769e-11e5-90ed-353ad8badc8f.png">

**Comment by micwallace** [comment]
Ok I just fixed a bug, pull master branch or replace 
/assets/js/wpos/sale.js and it should fix it.
Remember to clear browser cache after to make sure the changes take effect.

**Comment by razmir** [comment]
Replace it and now pos won't load with the following error.
<img width="1279" alt="screen shot 2015-10-19 at 21 48 10" src="https://cloud.githubusercontent.com/assets/15165634/10579534/245225f6-76ab-11e5-80aa-1c54e79eadf1.png">

**Comment by micwallace** [comment]
Try a git pull instead.

On 19 October 2015 11:49:15 pm AEST, razmir <notifications@github.com> wrote:
>Replace it and now pos won't load with the following error.
><img width="1279" alt="screen shot 2015-10-19 at 21 48 10"
>src="https://cloud.githubusercontent.com/assets/15165634/10579534/245225f6-76ab-11e5-80aa-1c54e79eadf1.png">
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/13#issuecomment-149218511

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by razmir** [comment]
Great, its working now!
Thanks a lot

**Comment by micwallace** [comment]
Good to hear, your welcome :-D

On 20 October 2015 12:12:55 am AEST, razmir <notifications@github.com> wrote:
>Great, its working now!
>Thanks a lot
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/13#issuecomment-149224908

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
