### ISSUE TITLE
Auto complete / item search failed for 600 more items

### ISSUE THREAD

**Issue by Djigoer** [micwallace/wallacepos#133]
We have more than 600 stored items, when we try to search item, there is nothing shown.
Is that because number of items exceed maximum of local storage?

**Comment by micwallace** [comment]
Can you please explain how the issue was resolved so others may benefit?

**Comment by Djigoer** [comment]
It was my mistake, there's item name which has unusual character
Hairfall Treatment Shampooÿ
The character **ÿ** somehow caused search item jammed.
After I get rid of it, the search item run well.
I think we must sanitize item name from unusual character like that when importing.
