### ISSUE TITLE
device has removed from the server

### ISSUE THREAD

**Issue by adheybgz1986** [micwallace/wallacepos#14]
im interested with this POS system but i have situation : 
pt 1 : 
i follow your installation and no error issue , after login as admin and run the feed server the status became online  but after i change the setting to my situation  and i double check the status feed server became offline  what is hppen? i logout admin dashboard and login again it happen again the feed server status became offline.  do i have to click start manually over and over ?

pt 2:
when succesfully registered device via admin ( eg : https://ksslite.co.id) and login it says : your device has removed from the server contact your administrator. so i login in the admin dashbord to make sure that i was registered at the unique UUID (see attch) . but i cant see the pos terminal . did i missing something ? 
![desktop 1_003](https://cloud.githubusercontent.com/assets/16421209/11990114/cc96197e-aa00-11e5-9fe4-38ecb95a0fc3.jpg)
![desktop 1_002](https://cloud.githubusercontent.com/assets/16421209/11990127/e2e76f16-aa00-11e5-8cd6-94e0e676c443.jpg)

Sorry my english is not verywell

thanks

**Comment by micwallace** [comment]
pt1:
Looks like node.js is failing to start. Some distros use the command node, whilst others use nodejs.
Try starting the feed server manually by running this command from the app root directory:
node api/server.js

If that command works you can simply create a symlink for nodejs to point to node

pt2:
What browser are you using? It may not contain the features required to run the POS terminal. Please try again with the latest version of chrome or firefox.

**Comment by micwallace** [comment]
Ok it seems that some hashing algorithm changes have caused a truncation error.
Run the following sql query on the database to correct pt2 problem:

```ALTER TABLE `device_map` CHANGE `uuid` `uuid` VARCHAR(64) NOT NULL;
