### ISSUE TITLE
please somebody help me how to install it from the ground up.I have a macbook. i am a newbie at github and i have no idea how to install projects downloaded from here.

### ISSUE THREAD

**Issue by sahilLikes2Code** [micwallace/wallacepos#141]
i found wallace pos online and it is a great piece of software as it tried it's demo online.I downloaded the clone or download file from github.i am using it with mamp on my mac and trying to create some database as per partial information i found online.I have no clue how to install/run or get it to work.Somebody expert in this field please help me fix it and achieve what the software is meant to do.
![screen shot 2018-07-04 at 4 52 03 pm](https://user-images.githubusercontent.com/40363532/42274538-ae659f56-7faa-11e8-9756-382be471434e.png)

**Comment by mckaygerhard** [comment]
well @sahil440 in that case are very more complicated rather your first attemp.. due this project implicated more tools that you complete not know so i recomend write me in the other issue
