### ISSUE TITLE
Initial setup for v1.4.3 throwing sql errors .. mysql 5.7 compatible?

### ISSUE THREAD

**Issue by Kashbin** [micwallace/wallacepos#148]
## Context
I have installed Php 7.2 and mysql  5.7
the application loads fine but while login I get this error popup.
![login_error](https://user-images.githubusercontent.com/6117472/46576620-5dc3e300-c99c-11e8-870d-0f00d2c551cf.PNG)

login successful , but get this error. Is walpos not compatible  with mysql 5.7 ?

![sql_error](https://user-images.githubusercontent.com/6117472/46576657-476a5700-c99d-11e8-868d-cdfed0026a5d.PNG)

I downloaded the source code with command:
git clone https://github.com/micwallace/wallacepos.git

Not sure this command downloaded the v1.4.3 release version. 

Please help me resolve these issues. I am trying to setup the development environment to contribute to.

Thanks. appreciate the help.

**Comment by micwallace** [comment]
It's compatible with 5.7 but you'll need to disable "only full group by" mode in mySQL:

https://stackoverflow.com/questions/23921117/disable-only-full-group-by

On 7 October 2018 10:22:38 AM AEDT, Kashbin Media Home <notifications@github.com> wrote:
>## Context
>I have installed Php 7.2 and mysql  5.7
>the application loads fine but while login I get this error popup.
>![login_error](https://user-images.githubusercontent.com/6117472/46576620-5dc3e300-c99c-11e8-870d-0f00d2c551cf.PNG)
>
>login successful , but get this error. Is walpos not compatible  with
>mysql 5.7 ?
>
>SQLSTATE[42000]: Syntax error or access violation: 1140 In aggregated
>query without GROUP BY, expression #1 of SELECT list contains
>nonaggregated column 'wpos_db.sales.id'; this is incompatible with
>sql_mode=only_full_group_by
>
>I downloaded the source code with command:
>git clone https://github.com/micwallace/wallacepos.git
>
>Not sure this command downloaded the v1.4.3 release version. 
>
>Please help me resolve these issues. I am trying to setup the
>development environment to contribute to.
>
>Thanks. appreciate the help.
>
>
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/148

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Kashbin** [comment]
Thanks. That worked using phpadmin console.
