### ISSUE TITLE
Compatible barcode scanner and printer device for Wallacepos

### ISSUE THREAD

**Issue by Kashbin** [micwallace/wallacepos#149]
I successfully setup the test environment locally on my machine. Registered my machine.
I wanted to start adding the stock/inventory. I am looking for barcode scanner and printer to add to the system.
Anybody know place where I can find them and how much it costs?

**Comment by Juliusyawson** [comment]
Is it compatible with barcode scanner? If yes, how do I add products/stock by using barcode.

**Comment by micwallace** [comment]
Any standard HID (keyboard emulated) scanner will work but you may need to configure the scanner to use an enter key suffix.

On 18 February 2019 6:44:03 pm AEDT, Juliusyawson <notifications@github.com> wrote:
>Is it compatible with barcode scanner? If yes, how do I add
>products/stock by using barcode.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/149#issuecomment-464620644

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Juliusyawson** [comment]
@micwallace 
Pls can you guide me on how to setup the barcode scanner?

**Comment by micwallace** [comment]
Nope, it's manufacturer specific. See you barcode scanner manual for steps to set the enter key as suffix.
