### ISSUE TITLE
node js : error

### ISSUE THREAD

**Issue by adheybgz1986** [micwallace/wallacepos#15]
root@kss:/var/www/api# nodejs server.js 
   info  - socket.io started
   warn  - error raised: Error: listen EADDRINUSE
root@kss:/var/www/api# 

what hppen ? im unable to see other device conected in realtime menu (admin panel). can u give me a hints ?
thanks for your time

**Comment by micwallace** [comment]
Hi,

That error is caused by another node.js process running on the same port.
Try running command:
killall nodejs
And then re-run the feed server.
If node starts but it still doesn't work then it is an issue with your apache config (wstunnel module specifically). Please go over the prerequisites in readme.md to make sure you have covered everything.

Cheers,
Michael

On 7 January 2016 4:51:30 pm AEDT, adheybgz1986 <notifications@github.com> wrote:
>root@kss:/var/www/api# nodejs serverjs 
>   info  - socketio started
>   warn  - error raised: Error: listen EADDRINUSE
>root@kss:/var/www/api# 
>
>what hppen ? im unable to see other device conected in realtime menu
>(admin panel) can u give me a hints ?
>thanks for your time
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/15

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by adheybgz1986** [comment]
Thanks for your fast response . ill try.

**Comment by adheybgz1986** [comment]
root@kss:/var/www/api# ps aux | grep nodejs
root      2382  0.0  0.0   3656   744 pts/1    S+   17:21   0:00 grep nodejs
root@kss:/var/www/api# killall nodejs
nodejs: no process found
root@kss:/var/www/api# nodejs server.js 
   info  - socket.io started
   warn  - error raised: Error: listen EADDRINUSE
root@kss:/var/www/api# 

stil no luck , try to reinstall npm still same , but its looks strange when i search socket.io location installation folder ( root of app /node_modules/socket.io/ ) its that okay ?
![errnde](https://cloud.githubusercontent.com/assets/16421209/12167192/a9d536de-b565-11e5-9d44-0b003cb9ef11.jpg)

**Comment by micwallace** [comment]
It sounds like apache is running on port 8080.
You can verify this by running:
netstat -tulpn

You may need to move node_modules to the api folder but I'm not certain.

On 7 January 2016 8:40:50 pm AEDT, adheybgz1986 <notifications@github.com> wrote:
>root@kss:/var/www/api# ps aux | grep nodejs
>root      2382  0.0  0.0   3656   744 pts/1    S+   17:21   0:00 grep
>nodejs
>root@kss:/var/www/api# killall nodejs
>nodejs: no process found
>root@kss:/var/www/api# nodejs server.js 
>   info  - socket.io started
>   warn  - error raised: Error: listen EADDRINUSE
>root@kss:/var/www/api# 
>
>stil no luck , try to reinstall npm still same , but its looks strange
>when i search socket.io location installation folder ( root of app
>/node_modules/socket.io/ ) its that okay ?
>![errnde](https://cloud.githubusercontent.com/assets/16421209/12167192/a9d536de-b565-11e5-9d44-0b003cb9ef11.jpg)
>
> 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/15#issuecomment-169610903

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by adheybgz1986** [comment]
thank you , now its working .
