### ISSUE TITLE
Cannot connect to feed server.

### ISSUE THREAD

**Issue by abhinavbalu** [micwallace/wallacepos#18]
The feed server goes offline automatically and if switched on manually it turns off automatically.

The server config:(Removed SSL didn't want it)

<VirtualHost 10.20.0.2:80>
         DocumentRoot /var/www/html/
         ServerName 10.20.0.2

         ErrorLog ${APACHE_LOG_DIR}/error.log
         CustomLog ${APACHE_LOG_DIR}/access.log combined
         
         <Directory /var/www/html>
            AllowOverride all
         </Directory>

         # WSPROXY CONF
         ProxyRequests Off
         ProxyPreserveHost On
         <Proxy 10.20.0.2>
                 Order deny,allow
                 Allow from all
         </Proxy>
         ProxyPass /socket.io/1/websocket/ ws://localhost:8080/socket.io/1/websocket/
         ProxyPassReverse /socket.io/1/websocket/ ws://localhost:8080/socket.io/1/websocket
         ProxyPass /socket.io/ http://localhost:8080/socket.io/
         ProxyPassReverse /socket.io/ http://localhost:8080/socket.io/
         <Location /socket.io>
                 Order allow,deny
                 Allow from all
         </Location>
    </VirtualHost>

**Comment by micwallace** [comment]
ServerName should be a domain name, not an IP address. 
Proxy path should be * not an IP address.

Try to run "nodejs api/server.js" manually to see what the error is.

**Comment by abhinavbalu** [comment]
Hi Micheal,
                 Will check and be back.

Regds,
Abhinav.

**Comment by micwallace** [comment]
Another thing to try is to make sure that Apache is not listening on port 8080.

**Comment by abhinavbalu** [comment]
Didn't get you.

**Comment by micwallace** [comment]
What's not to get? This may help:
https://github.com/micwallace/wallacepos/issues/22

**Comment by zaaaidi** [comment]
I am also facing this type of problem. Can you please help. And how can I run "nodejs api/server.js" manually to see what the error is ?
![screenshot_9](https://user-images.githubusercontent.com/20990312/39519885-facc5674-4e21-11e8-924e-2abd7391e31c.jpg)
