### ISSUE TITLE
Installation problem: SQLSTATE[28000] [1045] Access denied for user 'www-data'@'localhost' (using password: NO)'

### ISSUE THREAD

**Issue by captainwasabi** [micwallace/wallacepos#2]
I think this is saying it can't access the mysql database. Does the database need a user www-data with no password?

[Thu Apr 30 08:59:22.715398 2015] [:error] [pid 2737] [client 192.168.2.145:53860] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'www-data'@'localhost' (using password: NO)' in /usr/share/wallacepos-master/library/wpos/models/db/DbConfig.php:79\nStack trace:\n#0 /usr/share/wallacepos-master/library/wpos/models/db/DbConfig.php(79): PDO->__construct('mysql:host=loca...', '', '')\n#1 /usr/share/wallacepos-master/library/wpos/models/DbUpdater.php(28): DbConfig->__construct()\n#2 /usr/share/wallacepos-master/library/installer/index.php(33): DbUpdater->DbUpdater()\n#3 {main}\n\nNext exception 'PDOException' with message 'Failed to connect to database.' in /usr/share/wallacepos-master/library/wpos/models/db/DbConfig.php:89\nStack trace:\n#0 /usr/share/wallacepos-master/library/wpos/models/DbUpdater.php(28): DbConfig->__construct()\n#1 /usr/share/wallacepos-master/library/installer/index.php(33): DbUpdater->DbUpdater()\n#2 {main}\n  thrown in /usr/share/wallacepos-master/library/wpos/models/db/DbConfig.php on line 89

**Comment by captainwasabi** [comment]
Ok, I created user www-data and ran the install script.  I got this output: 

Setup Completed Successfully!
Please remove the install/index.php file after installing, leaving it after installation is dangerous

Nothing in the error.log

However, I go in with phpmyadmin and there are no tables created.

Looked in the install.sql file and it seems to indicate that the database is named 'dev' so I created that and gave the www-data all privs on it.  No dice, same results, it runs fine but no tables.

**Comment by captainwasabi** [comment]
ok, got it.  In library/wpos/models/db/DbConfig.php you have to set the username, password, and database for mysql.

**Comment by micwallace** [comment]
FYI You should use the method in the new readme.

Your usage has the same result but DbConfig.php may be replaced when updating.

**Comment by ferrites** [comment]
hello command to install wallacePos database schema in my localhost

**Comment by ferrites** [comment]
how can i install  wallacePos database schema in my localhost phpmyadmin

**Comment by micwallace** [comment]
Follow installation guide.
