### ISSUE TITLE
Your Install is broken, Wont connect to site once installed.

### ISSUE THREAD

**Issue by xymantec** [micwallace/wallacepos#22]
So after spending a few hours going over your software I was able to get it installed, once installed It can't connect to site?

![untitled-5](https://cloud.githubusercontent.com/assets/6463675/13690199/64f9ff04-e6e3-11e5-8c79-77363a43e35b.png)

Then the page gets stuck initializing...
![wallacepos](https://cloud.githubusercontent.com/assets/6463675/13690290/163ccd46-e6e4-11e5-9e49-9cef6bc9fac2.png)

all packages, file permissions are correctly installed and configured, I have checked it over 10 times. I get to the admin login page but this prevents it from even working or accepting posts.

**Comment by micwallace** [comment]
If it's not working then it is most likely your configuration that is the cause.

Please post your Apache virtual host configuration & look in the Apache error log for any clues.

**Comment by micwallace** [comment]
Go to the admin panel and try starting the feed server from settings -> utilities.
Log out and log back in to see if it works.

If not, try to run "nodejs api/server.js" manually to see what the error is.

**Comment by xymantec** [comment]
ok so I ran the command and it gave me a...

info  - socket.io started
warn  - error raised: Error: listen EADDRINUSE

Looked up the problem and it's caused by a port being used up that your app isn't able to use.
I did a nmap on the localhost and found this being the culprit, not sure but it seems like this is actually whats its suppose to be but I am not sure.

8080/tcp open  http-proxy

**Comment by micwallace** [comment]
Kill all nodejs processes and make sure Apache isn't listening on 8080.

**Comment by xymantec** [comment]
ok found the process that was causing the problem using "ps -ef | grep node" 

```
www-data  2307     1  0 18:23 ?        00:00:00 nodejs /var/www/api/server.js
root      2321  2284  0 18:26 pts/2    00:00:00 grep --color=auto node
```
I killed the process but I get then a socket error....
![untitled-6](https://cloud.githubusercontent.com/assets/6463675/13691906/6d4f682a-e6f1-11e5-93f7-f50abd6686c0.png)

after rebooting the server the problem disappears as long as I don't turn on the feed server.

**Comment by micwallace** [comment]
That error is to be expected when killing the feed server. Sounds like the connection is successful. 
Once you turn on the feed server you will need to logout and log back in to authorise the connection, otherwise the above error will be thrown.

**Comment by xymantec** [comment]
Thanks for your help, the problem seems resolved :)
