### ISSUE TITLE
Error installation Warning: file_put_contents

### ISSUE THREAD

**Issue by cheve** [micwallace/wallacepos#23]
When installing wallapop in step 2 configuration database displays this error: Warning: file_put_contents(/var/www/html/tpv_restaurante//library/wpos/.dbconfig.json): failed to open stream: Permission denied in /var/www/html/tpv_restaurante/installer/index.php on line 159.

Everything looks correct first step

<a href="http://subefotos.com/ver/?544d52852ddccae8592d05e993b09eb6o.jpg" target="_blank"><img src="http://thumbs.subefotos.com/544d52852ddccae8592d05e993b09eb6o.jpg" /></a>

Thanks

**Comment by micwallace** [comment]
Check the permissions of /var/www/html/tpv_restaurante/library/wpos/.dbconfig.json to make sure that www-data has write access.

I don't think it makes a difference but there is also an extra slash in the document root:
/var/www/html/tpv_restaurante//library/wpos/.dbconfig.json

Go to your apache virtual host config and change this:
DocumentRoot /var/www/html/tpv_restaurante/
to this:
DocumentRoot /var/www/html/tpv_restaurante
Just to make sure it isn't causing a problem.

Cheers,
Michael

**Comment by cheve** [comment]
Thanks Michael.
www-data does not have permissions. Extra slash i solved, my mistake.
Solved
