### ISSUE TITLE
Taxes Aren't Being Applied To Products.

### ISSUE THREAD

**Issue by xymantec** [micwallace/wallacepos#24]
I've tried altering or creating a new tax rule of 8% and it doesn't apply it to items. If i enter an item for $1.25 it calculates the tax but instead of incrementing to the total it subtracts from the item price so it equals the item price of $1.25

**Comment by micwallace** [comment]
Tax is inclusive of the item price by default. You need to change the tax rule to exclusive.

**Comment by xymantec** [comment]
Ok Awesome I got it to work now.
