### ISSUE TITLE
Must be logged in as admin

### ISSUE THREAD

**Issue by cutshaw** [micwallace/wallacepos#26]
Hey,

by now i solved all the issues i had by myself but after the installer finished i get this error. How may I be able to solve this, any ideas?
![bildschirmfoto vom 2016-04-11 17 26 21](https://cloud.githubusercontent.com/assets/18401361/14432601/21adf764-000b-11e6-9df6-a12335676425.png)

**Comment by micwallace** [comment]
Seems that the database is already installed or exists and the installer is trying to complete an upgrade instead. Check SQL and see if the database is populated.

**Comment by cutshaw** [comment]
The Database is populated as you can see in the screenshot. This error states that I must be logged in as admin on my local machine or is this an issue with the access to the mysql db?
![bildschirmfoto vom 2016-04-12 16 10 02](https://cloud.githubusercontent.com/assets/18401361/14462919/6746d37c-00c9-11e6-9758-ea5327885a7b.png)

**Comment by micwallace** [comment]
Nope it's talking about being logged in as WallacePOS admin in order to 
perform an upgrade.
The database setup looks like it was successful.
Go to /admin and see if you can login.

**Comment by cutshaw** [comment]
As you can see in the above screenshot I can´t get access to the server somehow ("There was an error connecting to the server: Not Found")
I want to test your POS for schooling purposes, simulating transactions on a local cloud.

**Comment by micwallace** [comment]
Well it sounds like a file can't be found.
Try checking the apache logs for further clues.

**Comment by cutshaw** [comment]
The apache logs state that whether /docs nor the config.json can be accessed.

![bildschirmfoto vom 2016-04-13 12 30 56](https://cloud.githubusercontent.com/assets/18401361/14490551/bb9ac384-0173-11e6-8c73-5ace3714f4f5.png)
![bildschirmfoto vom 2016-04-13 12 32 38](https://cloud.githubusercontent.com/assets/18401361/14490578/dac76bf4-0173-11e6-9041-34f09a1c3561.png)

**Comment by ais-one** [comment]
seems like the db settings could not be saved... /var/www/html/library/wpos/.dbconfig.json

check the DB settings in that file, or also, some of the files and folders need to be writable...

not sure which are the ones, but if you are just testing out first. Then just make permissions very liberal using command: chmod -R 777 /var/www/html/

**Comment by ais-one** [comment]
I am going to try and get it to work on xampp now (v5.6.19). This comment will be edited as I progress

1. enable mod_proxy_http & mod_proxy_wstunnel in <drive>\xampp\apache\conf\httpd.conf
mod_rewrite already enabled

2. curl and gd modules seem to also have been enabled
extension=php_curl.dll
extension=php_gd2.dll

3. edit <drive>\xampp\apache\conf\extra\httpd-vhosts.conf


````
<VirtualHost *:443>

DocumentRoot /xampp/htdocs/wpos
ServerName 127.0.0.1

#ErrorLog ${APACHE_LOG_DIR}/error.log
#CustomLog ${APACHE_LOG_DIR}/access.log combined

SSLEngine on
SSLCipherSuite !ADH:!DSS:!RC4:HIGH:+3DES:+RC4
SSLProtocol all -SSLv2 -SSLv3
SSLCertificateFile /xampp/apache/conf/ssl.crt/server.crt
SSLCertificateKeyFile /xampp/apache/conf/ssl.key/server.key

<Directory /xampp/htdocs/wpos >
	AllowOverride all
</Directory>

# WSPROXY CONF
ProxyRequests Off
ProxyPreserveHost On
<Proxy *>
	Order deny,allow
	Allow from all
</Proxy>
ProxyPass /socket.io/1/websocket/ ws://localhost:8080/socket.io/1/websocket/
ProxyPassReverse /socket.io/1/websocket/ ws://localhost:8080/socket.io/1/websocket
ProxyPass /socket.io/ http://localhost:8080/socket.io/
ProxyPassReverse /socket.io/ http://localhost:8080/socket.io/
<Location /socket.io>
	Order allow,deny
	Allow from all
</Location>
</VirtualHost>
````
Next nodejs, yucks...
1. download node,exe and npm and place it in the <drive>/xampp folder...
2. run npm install socket.io

T B Continued

**Comment by micwallace** [comment]
Thanks Aaron,

I've never used wamp myself and there's been a lot of questions from people about whether it will work. Thanks for pioneering this.

Keep in mind WallacePOS uses a small amount of bash commands to control the feed server (checkout WposSocketControl.php). I'll need to add windows equivalents for full support.

Cheers,
Michael

On 17 April 2016 1:48:55 am AEST, Aaron Gong <notifications@github.com> wrote:
>I am going to try and get it to work on xampp now (v5.6.19). This
>comment will be edited as I progress
>
>1. enable mod_proxy_http & mod_proxy_wstunnel in
><drive>\xampp\apache\conf\httpd.conf
>mod_rewrite already enabled
>
>2. curl and gd modules seem to also have been enabled
>extension=php_curl.dll
>extension=php_gd2.dll
>
>3. edit <drive>\xampp\apache\conf\extra\httpd-vhosts.conf
>
>
>````
><VirtualHost *:443>
>
>DocumentRoot /xampp/htdocs/wpos
>ServerName 127.0.0.1
>
>#ErrorLog ${APACHE_LOG_DIR}/error.log
>#CustomLog ${APACHE_LOG_DIR}/access.log combined
>
>SSLEngine on
>SSLCipherSuite !ADH:!DSS:!RC4:HIGH:+3DES:+RC4
>SSLProtocol all -SSLv2 -SSLv3
>SSLCertificateFile /xampp/apache/conf/ssl.crt/server.crt
>SSLCertificateKeyFile /xampp/apache/conf/ssl.key/server.key
>
><Directory /xampp/htdocs/wpos >
>	AllowOverride all
></Directory>
>
># WSPROXY CONF
>ProxyRequests Off
>ProxyPreserveHost On
><Proxy *>
>	Order deny,allow
>	Allow from all
></Proxy>
>ProxyPass /socket.io/1/websocket/
>ws://localhost:8080/socket.io/1/websocket/
>ProxyPassReverse /socket.io/1/websocket/
>ws://localhost:8080/socket.io/1/websocket
>ProxyPass /socket.io/ http://localhost:8080/socket.io/
>ProxyPassReverse /socket.io/ http://localhost:8080/socket.io/
><Location /socket.io>
>	Order allow,deny
>	Allow from all
></Location>
></VirtualHost>
>````
>Next nodejs, yucks...
>1. download node,exe and npm and place it in the <drive>/xampp
>folder...
>2. run npm install socket.io
>
>T B Continued
>
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/26#issuecomment-210843004

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by micwallace** [comment]
I've identified this as an error in the installer and it should be patched shortly.
