### ISSUE TITLE
"Please Balance The Sale Before Continuing" Error

### ISSUE THREAD

**Issue by xymantec** [micwallace/wallacepos#27]
So I have another error that continues to happen randomly, I get the "please balance the sale before continuing" prompt after trying to process a transactions that is balanced out.

Process > Cash > Complete and the error comes out, any ideas on how to fix this as it becomes a pain when we have clients in line.

![screenshot from 2016-04-12 16 31 50](https://cloud.githubusercontent.com/assets/6463675/14478613/21c341de-00cc-11e6-847c-6d94823c2f9b.png)

**Comment by micwallace** [comment]
Sorry to hear this is happening. Are you able to record the exact 
details of the sale so I can investigate?
- Items with unit cost, quantity, tax rule applied, etc
- Total shown

I have just tried using an exclusive rule on our development system and 
have not seen the problem.

**Comment by xymantec** [comment]
The pricing is on the screenshot, the tax rule is set to 8% non inclusive. I haven't put an vendors or items into inventory as I am still testing. Nothing special has been done or configured, it's just adding an item and adding pricing.

**Comment by micwallace** [comment]
Okay I have been able to reproduce this error. It's displayed only when cash rounding is disabled. I'll post a patch here shortly.

**Comment by xymantec** [comment]
Awesome :)

**Comment by micwallace** [comment]
Here you go:
https://github.com/micwallace/wallacepos/commit/2545f2b197096eb65fcdf2e1286b6826f0405e65
Replace sales.js with the new version and clear your browser cache to apply.

Thanks for reporting this issue.

**Comment by xymantec** [comment]
np brosiff :)
