### ISSUE TITLE
API calling is giving errors on demo site..

### ISSUE THREAD

**Issue by ramielian** [micwallace/wallacepos#28]
hi, the API calling for offline mode is given errors on demo site, is this project still maintained as we are trying to support you by merging it with a known ERP System for both benefits...

if the project is not maintained is it ok to take over ?!

**Comment by micwallace** [comment]
Hey,

The demo site should be working. We are aware of some issues last week which were fixed.
Please describe the issue in more detail if it is still occurring.

Yes this project is maintained, feel free to contribute via pull requests.
Which ERP are you merging with? Sounds interesting.

Cheers,
Michael

**Comment by ramielian** [comment]
Hi Michael…

 

We are trying to figure out a way to integrate the POS with ERPnext, its built on python and its open source, from the first look at Wallace pos I liked it, but after looking under the hood, I was surprised of the lack of promotions pricing real stock tracking and the way of tracking the stock…

 

We thought that integrating both ERPnext and Wallace will benefit both and complete both, but the ERP team have a surprise next week that’s why we have hold on the integration for now to see the surprise…

 

But still, we WILL make the integration soon enough…

 

Thanks

Mark

**Comment by micwallace** [comment]
Thanks for the feedback Mark.
