### ISSUE TITLE
Latest Version 2016-04-20 Issue - Linux & Windows

### ISSUE THREAD

**Issue by ais-one** [micwallace/wallacepos#35]
[FIXED]

Missing...

/assets/libs/datatables/datatables.min.js
/assets/js/wpos/eftpos.js
/assets/libs/datatables/datatables.min.css

After putting them in, can proceed, but then log in correctly (if wrong password get access denied)...

<br />
<b>Fatal error</b>:  Class 'CategoriesModel' not found in <b>/var/www/html/wpos/library/wpos/models/WposPosData.php</b> on line <b>319</b><br />

now checking on this...

**Comment by micwallace** [comment]
Looks like I've forgot to commit a few files. I'll fix it up when I get home.

On 20 April 2016 12:42:44 pm AEST, Aaron Gong <notifications@github.com> wrote:
>Missing...
>
>/assets/libs/datatables/datatables.min.js
>/assets/js/wpos/eftpos.js
>/assets/libs/datatables/datatables.min.css
>
>After putting them in, can proceed, but then log in correctly (if wrong
>password get access denied)...
>
>
><br />
><b>Fatal error</b>:  Class 'CategoriesModel' not found in
><b>/var/www/html/wpos/library/wpos/models/WposPosData.php</b> on line
><b>319</b><br />
>
>now checking on this...
>
>
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/35

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ais-one** [comment]
I am doing the CategoriesModel.php file fron scratch just for fun and to learn, the get is working, next edit then add :)

**Comment by micwallace** [comment]
That's my favorite way to learn. Use SuppliersModel as a reference, it's 
essentially the same.

**Comment by ais-one** [comment]
That's a great hint, I was using StoredItemsModel.php, my problem was the JSON, I could edit and add, but it would hang because although inserted to DB, the return for data was Null...

**Comment by ais-one** [comment]
Just downloaded the latest.

1. Editing of customers has a problem. It does not seem to be updating.

2. Also when creating an invoice, the customer list does not seem to be accurate.

Investigating these two issues.
