### ISSUE TITLE
Initializing blocked android devices

### ISSUE THREAD

**Issue by cheve** [micwallace/wallacepos#38]
I do not get access wallacepos new version Pos Terminal from Android devices. It freezes in initializing, Updating application... I tried with multiple devices and multiple browsers and same result.
From pc  localhost access without problems to Pos Terminal and Admin Dashboard.
It is related to permissions???

Thanks.

**Comment by ais-one** [comment]
Have you tried accessing the demo site using your Android device to see if it works?

demo.wallacepos.com

**Comment by micwallace** [comment]
I'm aware of a bug in the current pre-release, in which logging into the terminal the first time will hang but once refreshing the problem is gone.

However I think this is rather an installation issue. If you are upgrading you will need to run the installer to update the database:
https://YOURPOSDOMAIN/installer/index.php?upgrade&version=1.3

**Comment by cheve** [comment]
demo.wallacepos.com same thing happens.

**Comment by micwallace** [comment]
As mentioned I can't really determine the issue unless you provide more info.
Please look at the Javascript console to investigate further.

**Comment by ais-one** [comment]
I have tested on a few android mobile phones and tablets on demo.wallacepos.com, I do not see any issue.

Please include more detailed device information

**Comment by cheve** [comment]
Tested with two similar devices.
Connection Mode: devices----wifi----router----ethernet wire----server

OS: Android 4.1.2
Device 1: LG-430
Firefox browser freezes
Chrome Browser freezes
This device does not have today.

OS: Android 4.1.2
Device 2: LG-430
Firefox browser OK
Chrome Browser OK
Tint Browser freezes. Not as access tint browser JS console.

In the device 2 with firefox and chrome to access as administrator displays this message:
there was an error connecting to the webserver & files needed to run offline are not present.
please check your connection and try again.

This afternoon try device 1 and include log of firefox JS console. Excuse me.

Thanks

**Comment by ais-one** [comment]
Looks like something to do with your network connection.

I suppose the network you are using has no connection to the internet.

I am using Chrome and the built in browser, no issues. LG G4, Sony Z1 Compact. They are android version 5 and above though...

**Comment by cheve** [comment]
Sorry for the delay. I actualized to Lubuntu 16.04 LTS to accompany new version wallacepos for testing. Installed again firefox, chrome and Tint Browser to devices 1 & 2.
On the new testing everything run right in localhost and demo.wallacepos.com, except Tint Browser that freezes in TerminalPos initializing. That will be the problem of Tint Browser application.

I think you can close the post. I have to open another post for another problem!!!
Thanks

**Comment by xymantec** [comment]
I am actually experiencing the same problem. I can access the the POS as long as its from the local host but any other device on the network gets stuck on initializing. This only happens for users, I can still long into admin panel from any device.

**Comment by micwallace** [comment]
Thanks for providing console output. 
I think this is an issue caused when registering a new device from the terminal.
I don't think it will occur if you add a device from admin and then register as an existing device.

To re-register a device, delete the wpos_uuid local storage value (you can do this using firebug DOM editor).

There also seems to be an issue loading cache manifest but that is a separate problem which will prevent offline mode from working.
Try accessing wpos.appcache from the browser and post the output.

**Comment by xymantec** [comment]
I have actually already tried adding the device from the admin panel thinking it was probably a glitch with the UI on the client side but ended up with the same result.

Here is the copy of the wpos.appcache printout:

_CACHE MANIFEST
# v4d518efbba60ef84ce0a5f203668bf59

CACHE:
/index.html
/assets/libs/socketio/WebSocketMain.swf
/assets/libs/socketio/socket.io.min.js
/assets/libs/socketio/socket.io.js
/assets/libs/socketio/WebSocketMainInsecure.swf
/assets/libs/WebPrint.jar
/assets/libs/qz-print/qz-print-wpos.js
/assets/libs/qz-print/qz-print.jar
/assets/libs/qz-print/lib/jssc_qz.jar
/assets/libs/qz-print/lib/pdf-renderer_qz.jar
/assets/libs/qz-print/qz-print_jnlp.jnlp
/assets/libs/qz-print/js/jquery.plugin.html2canvas.js
/assets/libs/qz-print/js/deployJava.js
/assets/libs/qz-print/js/jquery-1.10.2.js
/assets/libs/qz-print/js/html2canvas.js
/assets/libs/qz-print/js/PluginDetect.js
/assets/libs/jquery-keypad/jquery.keypad.css
/assets/libs/jquery-keypad/jquery.keypad.min.js
/assets/libs/jquery-keypad/keypad.png
/assets/libs/jquery-keypad/jquery.plugin.min.js
/assets/images/icon.png
/assets/images/apple-touch-icon-72x72.png
/assets/images/ajax-loader.gif
/assets/images/receipt-logo-mono.png
/assets/images/receipt-logo.png
/assets/images/apple-touch-icon-114x114.png
/assets/images/apple-touch-icon.png
/assets/images/favicon.ico
/assets/images/receipt-logo-mono-master.png
/assets/images/qrcode.png
/assets/font/DXI1ORHCpsQm3Vp6mXoaTXhCUOGz7vYGh680lGh-uXM.woff
/assets/font/fontawesome-webfont.ttf
/assets/font/FontAwesome.otf
/assets/font/fontawesome-webfont.svg
/assets/font/fontawesome-webfont.woff
/assets/font/fontawesome-webfont.eot
/assets/font/cJZKeOuBrn4kERxqtaUH3T8E0i7KZn-EPnyo3HZu7kw.woff
/assets/css/font-awesome.min.css
/assets/css/ace-ie.min.css
/assets/css/ace.min.css
/assets/css/jquery-ui-1.10.3.full.min.css
/assets/css/wpos.css
/assets/css/ace-fonts.css
/assets/css/ace-rtl.min.css
/assets/css/font-awesome-ie7.min.css
/assets/css/bootstrap.min.css
/assets/js/jquery-ui-1.10.3.full.min.js
/assets/js/bootstrap.min.js
/assets/js/jquery-1.10.2.min.js
/assets/js/jquery.mobile.custom.min.js
/assets/js/wpos/utilities.js
/assets/js/wpos/sales.js
/assets/js/wpos/print.js
/assets/js/wpos/core.js
/assets/js/wpos/reports.js
/assets/js/wpos/transactions.js
/assets/js/wpos/orders.js
/assets/js/jquery.scannerdetection.js
/assets/js/jquery-2.0.3.min.js
/assets/js/typeahead-bs2.min.js
/assets/img/glyphicons-halflings-white.png
/assets/img/clear.png
/assets/img/loading.gif
/assets/img/glyphicons-halflings.png
/assets/sounds/bell_modern.mp3
/docs/receipt-logo-mono.png
/docs/receipt-logo.png
/docs/qrcode.png

NETWORK:
/api/*
/wpos.appcache
http://*
https://*
*

FALLBACK:
/assets/font/cJZKeOuBrn4kERxqtaUH3T8E0i7KZn-EPnyo3HZu7kw.woff assets/font/cJZKeOuBrn4kERxqtaUH3T8E0i7KZn-EPnyo3HZu7kw.woff
/assets/font/DXI1ORHCpsQm3Vp6mXoaTXhCUOGz7vYGh680lGh-uXM.woff assets/font/DXI1ORHCpsQm3Vp6mXoaTXhCUOGz7vYGh680lGh-uXM.woff
/assets/font/fontawesome-webfont.woff assets/font/fontawesome-webfont.woff
/assets/font/fontawesome-webfont.eot assets/font/fontawesome-webfont.eot
/assets/font/fontawesome-webfont.svg assets/font/fontawesome-webfont.svg
/assets/font/fontawesome-webfont.ttf assets/font/fontawesome-webfont.ttf
/assets/font/fonts/FontAwesome.otf assets/font/FontAwesome.otf_

**Comment by micwallace** [comment]
The cache manifest issue is caused by an invalid certificate:
http://stackoverflow.com/questions/28507846/manifest-fetch-failed-9

Investigating the other issue shortly.

**Comment by xymantec** [comment]
If that were so wouldn't it be causing the same issue for the admin panel as well? I'm I am going to remove ssl temporarily to verify this indeed is the issue.

**Comment by micwallace** [comment]
The admin panel isn't cached so it shouldn't be related.

I've just pushed out an update which should fix this:
core.js:825 Uncaught TypeError: Cannot read property 'type' of null

Although I'm not sure of the underlying cause.
Let me know if it fixes the issue.

**Comment by xymantec** [comment]
Ok I can can confirm it's a problem with SSL certs on the loading resources hang-up, I will purchase a 3rd party verified ssl cert tomorrow and see if it works again with a valid/3rd party verified cert and ssl enabled.

**Comment by micwallace** [comment]
I think torch browser may have some web features disabled that are needed by the terminal.
I've added a compatibility check on start-up that will check for required localStorage and applicationCache.
f387e49

I also fixed an issue with font paths in wpos.appcache which was actually causing the manifest load issue in chrome.
