### ISSUE TITLE
Cant connect to host

### ISSUE THREAD

**Issue by captainwasabi** [micwallace/wallacepos#4]
Reinstalled mysql, reinitialized.

Try to login as admin/admin and it gives a message box saying it "couldn't connect to host"

no weirdness in the console or network tools.  If I try logging in with the wrong password it fails properly, so it is actually getting past the login before failing. :(

**Comment by micwallace** [comment]
You need to start the feed-server, however I've prevented this error from being fatal in the latest update.

Also, I've updated the readme with a full install guide.
