### ISSUE TITLE
sales.data bug if data exceeds 4096 bytes

### ISSUE THREAD

**Issue by ais-one** [micwallace/wallacepos#45]
if the number of items is a lot and causes data field to exceed 4096 bytes, there will be a problem when accessing transactions, javascript will crash.

We need to:

1) increase the size of the sales.data field

2) do an error when there is too many items

Will help look into this

**Comment by micwallace** [comment]
Hi Aaron,

We should definitely migrate to a JSON type field. This has the added benefit of being able to access the JSON values using SQL directly but is only available in 5.7:

https://dev.mysql.com/doc/refman/5.7/en/json.html

**Comment by ais-one** [comment]
Ah ok, let me test it on 5.7 then, looks like I am forced to use 5.7
earlier :)

**Comment by ais-one** [comment]
working on this issue now. 

C:\xampp\htdocs\wpos\assets\js\wpos\sales.js

- ProcessSaleTransaction()

- processOrder()

Will create an alert in the two functions above if data size exceeds and abort with warning.

**Comment by ais-one** [comment]
one function seems to be missing... - WPOS.trans.showTransactionTable()...

**Comment by ais-one** [comment]
One more fix to commit, the part regarding alert user if too many items

**Comment by micwallace** [comment]
How many items are needed to make this error occur? Should we increase the size?

I'd like to use the JSON column type for future versions but we should keep is as varchar in v1.3 for legacy reasons. I'll be looking into mysql 5.7 support later today.

**Comment by ais-one** [comment]
Thanks Michael, I will find some time to try it out with mysql 5.7, looking at the GROUP BY issue (follow up from there) and the JSON data type.

**Comment by ais-one** [comment]
Hi Mike,

If you set the field size to 1000 bytes instead of 4096, it takes about
after the 3rd item, there is problem.

What you can do to assist in your research is to do console.log( length of
json ) at those place where I had put the string length checks, that will
help you get a better visibility...





*Warmest Regards,*

*Aaron*


The information herein is given on a general basis without obligation and
is strictly for information purposes only. We do not warrant the accuracy
or completeness of the information, graphics, links, or other items
contained herein, and expressly disclaim liability for errors or omissions
in these materials.

**Comment by micwallace** [comment]
Okay that's not good at all!

I'm going to jack the length up to 16384. That should allow for maximum of 48 items.
I'm fairly certain that most of our users will not go over that.

In future versions we will mitigate this issue by using JSON type. We can also provide legacy mySQL support by using a separate schema.

**Comment by ais-one** [comment]
Hi Michael,

If most of the things in data are blank it will be smaller, the 1000 bytes,
about 800+ bytes was not regarding the items.

The items I tested on only have Name (about 6 characters), Price, StockCode.

But yes, it is ok, to push it to 16384 just in case.




*Warmest Regards,*

*Aaron*


The information herein is given on a general basis without obligation and
is strictly for information purposes only. We do not warrant the accuracy
or completeness of the information, graphics, links, or other items
contained herein, and expressly disclaim liability for errors or omissions
in these materials.

**Comment by ais-one** [comment]
Hi Michael,

If most of the things in data are blank it will be smaller, the 1000 bytes,
about 800+ bytes was not regarding the items.

The items I tested on only have Name (about 6 characters), Price, StockCode.




*Warmest Regards,*

*Aaron*


The information herein is given on a general basis without obligation and
is strictly for information purposes only. We do not warrant the accuracy
or completeness of the information, graphics, links, or other items
contained herein, and expressly disclaim liability for errors or omissions
in these materials.

**Comment by micwallace** [comment]
f00de93
Sales table data field increased.
