### ISSUE TITLE
Invoice Logo

### ISSUE THREAD

**Issue by vegapaul** [micwallace/wallacepos#49]
When generating invoice logo does not generate.
![invoice logo](https://cloud.githubusercontent.com/assets/18123313/15636755/0d38902c-25d7-11e6-98b1-4e78d61a894e.png)

**Comment by vegapaul** [comment]
Ay update on this?

**Comment by micwallace** [comment]
If you would like to expedite this bug, please make a small donation to the project.

**Comment by micwallace** [comment]
I can't seem to reproduce this issue. This is shown when the image set for business logo isn't found. What do you have set as the logo?

**Comment by micwallace** [comment]
You will have to provide more information. 
Create another issue using the issues template.
