### ISSUE TITLE
Socket Authentication Failed on /admin/#!realtime

### ISSUE THREAD

**Issue by JesusIslam** [micwallace/wallacepos#51]
Already run `node server.js` on the `api` directory, but it keeps failing to authenticate.

How do I fix this?

These are the logs:

```
info  - socket.io started
   debug - client authorized
   info  - handshake authorized P0O4a4j4WCclmfYUl7h8
   debug - setting request GET /socket.io/1/websocket/P0O4a4j4WCclmfYUl7h8
   debug - set heartbeat interval for client P0O4a4j4WCclmfYUl7h8
   debug - client authorized for 
   debug - websocket writing 1::
   debug - websocket writing 5:::{"name":"updates","args":[{"a":"error","data":"Socket authentication failed!"}]}
   info  - booting client
   info  - transport end by forced client disconnection
   debug - websocket writing 0::
   info  - transport end (booted)
   debug - set close timeout for client P0O4a4j4WCclmfYUl7h8
   debug - cleared close timeout for client P0O4a4j4WCclmfYUl7h8
   debug - cleared heartbeat interval for client P0O4a4j4WCclmfYUl7h8
   debug - discarding transport

```

**Comment by micwallace** [comment]
Once starting the socket server, you need to logout and log back in. Your session will then become authorised with the feed server.

**Comment by JesusIslam** [comment]
Still failed with same errors.

For the information, I ran Apache to listen to port 8080 and the socket server to 8081. I don't know if this helps.

**Comment by micwallace** [comment]
More information always helps!

In that case you'll also need to change the port here:
https://github.com/micwallace/wallacepos/blob/master/library/wpos/models/WposSocketIO.php#L43

**Comment by JesusIslam** [comment]
Ok, it works now. Thank you very much. I think this should be documented somewhere in case people need to use different listening ports.

**Comment by micwallace** [comment]
Thanks I will add it to the documentation in the next round of edits.

**Comment by micwallace** [comment]
I've added the ability to change the port from the admin interface in the next version.
