### ISSUE TITLE
Can't create new locations

### ISSUE THREAD

**Issue by RobertMTTECH** [micwallace/wallacepos#52]
Hi friends,
I got "insertion of new location failed" when i tried to register new device at the first setup.
Can you help me to solve this?

**Comment by micwallace** [comment]
Hey Robert,

Did you find out what caused this?
I'll look at reworking that so it gives a more specific error, most likely a database issue.

**Comment by RobertMTTECH** [comment]
Hi friend,

I took many errors and researched all issue posted here.
Finally, i decided to reinstall and did sequense tasks:
1. Install OS
2. Install LAMP, configure all nessary requirements before clone this project to Document Root path
3. Install and get work!

It works well since then.
Thanks a lot, guy! Your project is very usefull!
