### ISSUE TITLE
Invoices Section Empty

### ISSUE THREAD

**Issue by solancer** [micwallace/wallacepos#53]
I'm unable to fund any invoices under the section. Please find the screen shot below

![screenshot from 2016-07-12 02 31 57](https://cloud.githubusercontent.com/assets/800668/16746670/075310be-47d9-11e6-9c04-e6d5a80f15cd.png)
![screenshot from 2016-07-12 02 32 09](https://cloud.githubusercontent.com/assets/800668/16746671/079ace0e-47d9-11e6-96ce-40d6f6680850.png)

**Comment by micwallace** [comment]
Maybe because you have not created any invoices?

POS sales get displayed under "POS Sales".
