### ISSUE TITLE
Problem with feed server

### ISSUE THREAD

**Issue by RobertMTTECH** [micwallace/wallacepos#54]
Hi,

I found many solved issue in this repository. But still stuck in it.
![feedserver](https://cloud.githubusercontent.com/assets/20390605/16828600/64a5ef82-49bb-11e6-81f7-4c5a8511c5a9.png)
![nodejs](https://cloud.githubusercontent.com/assets/20390605/16828601/64ccadf2-49bb-11e6-904f-68b5a7306e2d.png)

Please help me!

**Comment by micwallace** [comment]
I think you may need version socket.io 0.9.x installed instead.

Try:
`npm install socket.io@0.9.17`

**Comment by RobertMTTECH** [comment]
Thanks for your help!
