### ISSUE TITLE
Application Cache Error event: Failed to parse manifest

### ISSUE THREAD

**Issue by solancer** [micwallace/wallacepos#55]
Staff logins is not working because of app cache manifest errors.

I've updated the .htaccess file with the appropriate rules.

AddType application/x-httpd-php .appcache
<IfModule mod_expires.c>
  <Files *.appcache>
      ExpiresActive On
      ExpiresDefault "access plus 0 seconds"
  </Files>
</IfModule>

This is the link to my appcache https://pos.westcoast-india.co.in/wpos.appcache

Below is the screenshot of the errors in web console.

![screenshot from 2016-07-13 18 04 31](https://cloud.githubusercontent.com/assets/800668/16835986/e44859c4-49d8-11e6-9cb2-9e3485bc444f.png)

**Comment by micwallace** [comment]
I don't think this is to do with appcache but possibly another problem with the api login call. Can you please have a look at the login request from the dev tools network tab and provide response output?

**Comment by solancer** [comment]
![screenshot from 2016-07-25 17 04 36](https://cloud.githubusercontent.com/assets/800668/17100080/f98153f4-5289-11e6-9d41-24b86945614c.png)

**Comment by solancer** [comment]
I've sent you an email with more details

**Comment by solancer** [comment]
![screenshot from 2016-08-07 15-56-26](https://cloud.githubusercontent.com/assets/800668/17461857/915c0e58-5cb7-11e6-9175-0173d14daec7.png)

**Comment by micwallace** [comment]
I just had a quick look.
I can reproduce on your server, however it seems to be an app environment issue since I can't reproduce elsewhere. You will have to troubleshoot this issue further, here are my findings so far:

- Seems to be an issue with session storage.
- The login api call returns null, here is where that occurs: https://github.com/micwallace/wallacepos/blob/master/library/wpos/Auth.php#L77
- I have updated https://github.com/micwallace/wallacepos/blob/master/api/wpos.php#L54 with code that will detect this error and return an error message. Replace this file in your installation. If you get the error you will be able to confirm a php session issue. Next steps would be to check that you have the right php version and sessions are working.
- Try to create another user and see if you can reproduce the error.

**Comment by solancer** [comment]
I was not able to login with staff but when I deleted the user and recreated it I was able to login with it. I also created a new user called test and I was able to login with that user just fine.

After replacing the new api/wpos.php from the repo I checked with the logs and saw that everything was working fine.

Also I was not able to replace the file without changing the permission 

`sudo chown -R srini.www-data /var/www/html/`

after this I was able to write to the folder with the new file but the app was not working(permission issues)

so I had to go ahead and change back the permissions to 

`sudo chown -R www-data.srini /var/www/html/`

and things seem to be working fine now expect for a error about websocket connection

![screenshot from 2016-08-08 15-56-29](https://cloud.githubusercontent.com/assets/800668/17477263/e8bfb620-5d81-11e6-9a3a-22a612eb7877.png)

**Comment by micwallace** [comment]
Seems to be an issue with socket.io:
https://github.com/socketio/socket.io/issues/2543

**Comment by solancer** [comment]
Also I see that some permissions are not right any pointers on that?

![screenshot from 2016-08-08 16-30-15](https://cloud.githubusercontent.com/assets/800668/17477874/7a47781e-5d85-11e6-833d-82ec987b2b1e.png)

**Comment by micwallace** [comment]
```
cd /var/www/html/
chgrp -R www-data .
find . -type d -exec chmod 750 {} \;
find . -type f -exec chmod 640 {} \;
chmod 660 ./library/wpos/.config.json
chmod 660 ./library/wpos/.dbconfig.json
```

**Comment by equinenigeria** [comment]
i get this on login page firefox. Your browser does not support applicationCache and will not be able to function offline. Any help??

**Comment by micwallace** [comment]
Yes unfortunately applicationCache has been depreciated, in favor of the CacheAPI: 
[https://blog.chromium.org/2020/01/appcache-scope-restricted.html](https://blog.chromium.org/2020/01/appcache-scope-restricted.html)
This project isn't actively maintained so I'm not planning to update it to be compatible with CacheAPI

This means that wallacePOS will no longer be able to be loaded offline going forward. However if you already have it loaded in the browser and connection is lost, it will still function in offline mode.

**Comment by equinenigeria** [comment]
Thank you micwallace. Can you recommend someone for me to help with fixing it for me and other stuffs i need it to do. thank you.
RegardsIsrael

    On Tuesday, June 23, 2020, 7:17:04 AM GMT+1, micwallace <notifications@github.com> wrote:  
 
 


Yes unfortunately applicationCache has been depreciated, in favor of the CacheAPI:
https://blog.chromium.org/2020/01/appcache-scope-restricted.html
This project isn't actively maintained so I'm not planning to update it to be compatible with CacheAPI

This means that wallacePOS will no longer be able to be loaded offline going forward. However if you already have it loaded in the browser and connection is lost, it will still function in offline mode.
