### ISSUE TITLE
Fatal error: Call to undefined function apache_get_modules() in /home/c6mucr2h/public_html/wallace/installer/index.php on line 74

### ISSUE THREAD

**Issue by leominojr** [micwallace/wallacepos#56]
Fatal error: Call to undefined function apache_get_modules() in /home/c6mucr2h/public_html/wallace/installer/index.php on line 74 and apache version error too please help me I can't install wallace

**Comment by micwallace** [comment]
It seems you are using shared hosting. Please note that the POS may not be compatible with your environment. It is up to you to confirm that all dependencies are met via the configuration guide, we do not provide free support for unknown environment.

See the following explanation for the error you are experiencing:
http://stackoverflow.com/questions/3178173/alternatives-to-apache-get-modules-to-get-list-of-loaded-apache-modules
PHP should be installed via the Apache module, not CGI.
