### ISSUE TITLE
Cash Reconciliation

### ISSUE THREAD

**Issue by OmarSari** [micwallace/wallacepos#59]
What does Cash Reconciliation means in POS?

Sincerely

**Comment by micwallace** [comment]
It allows you to check that cash payments balance. At the end of the day you enter denominations for cash on hand, minus the float and it will tell you if it balances.

On 8 September 2016 2:37:45 PM AEST, OmarSari <notifications@github.com> wrote:
>What does Cash Reconciliation means in POS?
>
>Sincerely
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/59

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
