### ISSUE TITLE
OrangePi Plus 2 + Debian + Wallacepos

### ISSUE THREAD

**Issue by cheve** [micwallace/wallacepos#60]
Installed Wallacepos in Debian 8.5
<a href="http://subefotos.com/ver/?a28dc9b51120534e2b453489755e4435o.jpg" target="_blank"><img src="http://thumbs.subefotos.com/a28dc9b51120534e2b453489755e4435o.jpg" /></a>

Unfortunately not install all SQL tables.

Tax data could not be retrieved: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wallacepos.tax_items' doesn't exist

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wallacepos.sale_items' doesn't exist

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wallacepos.devices' doesn't exist

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wallacepos.stored_categories' doesn't exist

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wallacepos.stock_levels' doesn't exist

<a href="http://subefotos.com/ver/?ff758432d0590379b93a82a68429acado.jpg" target="_blank"><img src="http://thumbs.subefotos.com/ff758432d0590379b93a82a68429acado.jpg" /></a>

Another way to install db sql???

Thanks.

**Comment by micwallace** [comment]
Does the mysql user used for wallacePOS have permissions to add tables? I think you may need to add the target database first.

You can simply run /library/installer/install.sql against your database to populate the tables.

**Comment by cheve** [comment]
thanks micwallace.
To import install.sql in wallacepos db returns this error:

CREATE TABLE IF NOT EXISTS `devices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(66) NOT NULL,
  `locationid` int(11) NOT NULL,
  `data` varchar(2048) NOT NULL,
  `dt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `disabled` int(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_unicode_ci;

#1067 - Invalid default value for 'dt' 

Searching in sql docs: [http://dev.mysql.com/doc/refman/5.0/en/data-type-defaults.html](http://dev.mysql.com/doc/refman/5.0/en/data-type-defaults.html)

CURRENT_TIMESTAMP is only acceptable on TIMESTAMP fields. In mysql 5.6.5, you can use CURRENT_TIMESTAMP with DATETIME fields. I use mysql 5.5 and apparently does not support it. I tried it on another machine with MySQL 5.7 and works.

Any idea???

Thanks

**Comment by micwallace** [comment]
Try removing all instances of "NOT NULL DEFAULT CURRENT_TIMESTAMP" from install.sql

Alternatively you could try the install.sql from release 1.3 rather than master branch.

On 18 September 2016 4:33:04 PM AEST, cheve <notifications@github.com> wrote:
>thanks micwallace.
>To import install.sql in wallacepos db returns this error:
>
>CREATE TABLE IF NOT EXISTS `devices` (
>  `id` int(11) NOT NULL AUTO_INCREMENT,
>  `name` varchar(66) NOT NULL,
>  `locationid` int(11) NOT NULL,
>  `data` varchar(2048) NOT NULL,
>  `dt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
>  `disabled` int(1) NOT NULL DEFAULT 0,
>  PRIMARY KEY (`id`)
>) ENGINE=MyISAM DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_unicode_ci;
>
>#1067 - Invalid default value for 'dt' 
>
>Searching in sql docs:
>[http://dev.mysql.com/doc/refman/5.0/en/data-type-defaults.html](http://dev.mysql.com/doc/refman/5.0/en/data-type-defaults.html)
>
>CURRENT_TIMESTAMP is only acceptable on TIMESTAMP fields. In mysql
>5.6.5, you can use CURRENT_TIMESTAMP with DATETIME fields. I use mysql
>5.5 and apparently does not support it. I tried it on another machine
>with MySQL 5.7 and works.
>
>Any idea???
>
>Thanks
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/60#issuecomment-247828939

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cheve** [comment]
Removing all instances of "NOT NULL DEFAULT CURRENT_TIMESTAMP" from install.sql has been fixed. Thanks again micwallace.
I also try install.sql from release 1.3 rather than master branch.

SOLVED. Thanks
