### ISSUE TITLE
SQL queries processdt for Graphs are wrong

### ISSUE THREAD

**Issue by pwnyxxxpress** [micwallace/wallacepos#61]
The Sale Graph on the dashboard and Graph page aren't showing any results. Dug deeper and noticed the date ranges for the Graph page are going from Thu, 01 Sep 2016 04:00:00 GMT (1472702400000) to Sun, 20 Oct 1957 04:24:32 GMT('-384982528) when I was expecting ranges between Sept 13 to Sept 20 2016. The Sale Stats on the Dashboard are updating properly though.

DB query log. Note the processdt ranges

551 Connect systempos@localhost on posdb
551 Query   SET time_zone = '+00:00'
550 Query   SELECT *, d.id as groupid, d.name as name, SUM(s.total) as stotal, COUNT(s.id) as snum, COALESCE(GROUP_CONCAT(s.ref SEPARATOR ','),'') as refs FROM sales as s LEFT JOIN locations as d ON s.locationid=d.id WHERE (s.processdt>= '1472702400000' AND s.processdt<= '-384982528') AND status!= '3' GROUP BY s.locationid
550 Query   SELECT *, d.id as groupid, d.name as name, SUM(s.total) as stotal, COUNT(s.id) as snum, COALESCE(GROUP_CONCAT(s.ref SEPARATOR ','),'') as refs FROM sales as s LEFT JOIN locations as d ON s.locationid=d.id WHERE (s.processdt>= '1472702400000' AND s.processdt<= '-384982528') AND status= '3' GROUP BY s.locationid
551 Query   SELECT *, d.id as groupid, d.name as name, SUM(v.amount) as stotal, COUNT(v.id) as snum, GROUP_CONCAT(s.ref SEPARATOR ',') as refs FROM sale_voids as v LEFT JOIN sales as s ON v.saleid=s.id LEFT JOIN locations as d ON v.locationid=d.id WHERE (v.processdt>= '1472702400000' AND v.processdt<= '-384982528') AND v.void= '0' GROUP BY v.locationid
550 Quit    
## Process
1. Fresh install
2. Add some POS sales
3.  Sale Graph on the dashboard and Graph page don't update
## Expected result

Expected Sale Graph on the dashboard and Graph page to update with data.
## Current result

Sale Graph on the dashboard and Graph page don't update with data.
## Possible Fix

Not sure yet still looking into it.
## screenshot

n/a

**Comment by micwallace** [comment]
Check the output of the browser console to view the output of the api call. If your using mysql 5.7 you may need to disable ONLY_FULL_GROUP_BY:
http://stackoverflow.com/questions/23921117/disable-only-full-group-by

**Comment by micwallace** [comment]
Sorry I read over the part about the invalid timestamp. You'll hae to debug what parameters the UI is sending in /admin/content/graph.php. Try another browser and see if you get the same.

**Comment by pwnyxxxpress** [comment]
Removing the intval calls in the link below fixed the issue. My server is 32 bit and can't process the large epoch dates with intval.

https://github.com/micwallace/wallacepos/blob/13bba0b366a08592a22945d7c2e0ea0e33c6638f/library/wpos/models/WposAdminGraph.php#L63
