### ISSUE TITLE
Multilingual support / Internationalization

### ISSUE THREAD

**Issue by globalcitizen** [micwallace/wallacepos#62]
It seems from the test installation's admin console that there is no multilingual support. This was my query. You should probably make that explicit somewhere to save others time.
## Context

Friends starting bar in China; need Chinese support on printed receipts (interface not important).
## Process
1. Go to Github, no mention of i18n
2. Go to website, no mention of i18n
3. Go to features page, no mention of i18n
4. Go to questions section, "If you have a good question, suggest it!" This is that suggestion.
## Expected result

i18n support explained.
## Current result

No mention of i18n.
## Possible Fix

Add question to FAQ.

**Comment by micwallace** [comment]
Hi there, there are no current plans to implement i18n at this time. Many people have approached me for full internationalisation but it is a bit job and nobody wants to pay for it.

However, there is already the ability to print multilingual receipts via browser printing or bitmap printing mode through webprint (for receipt printers).
