### ISSUE TITLE
Feature request: profit calculation

### ISSUE THREAD

**Issue by donnykurnia** [micwallace/wallacepos#63]
I'm interested in using this POS, might be adding features to it. Any plan to add a feature for profit calculation?

Feature overview:

1. each item had a base price
2. for every sale, the profit is calculated from sale price - base price
3. The profit will appear in the daily report per item and might be on other reports as needed.

**Comment by micwallace** [comment]
This is on the list but probably won't be completed until later next year.

**Comment by micwallace** [comment]
https://github.com/micwallace/wallacepos/releases/tag/1.4.1
