### ISSUE TITLE
Not able to setup on Linux dedicated hosting

### ISSUE THREAD

**Issue by opensourceexpert** [micwallace/wallacepos#65]
Hi Have followd the steps mentioned to setup the application on local as well as the dedicated linus server(both with apache)
Iam getting following error

SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

This happens when I click on login button. Please letme know if I am missing anything.

**Comment by micwallace** [comment]
In the browser developer tools, go to networking and view the response from the server. That should give you some clues.

**Comment by micwallace** [comment]
This is usually because apache mod_rewrite is not enabled.

**Comment by opensourceexpert** [comment]
I just crosschecked mod_rewrite is enabled on the server.

**Comment by micwallace** [comment]
What version of apache are you using?

**Comment by opensourceexpert** [comment]
Thanks for replying back. Here are my environment details:

Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-43-generic x86_64)
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Jul 24 2015 17:25:11
PHP 5.5.9-1ubuntu4.20 (cli) (built: Oct  3 2016 13:00:37)
mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.3


root@server:~# a2enmod rewrite
Module rewrite already enabled

**Comment by micwallace** [comment]
Okay I'm sure it's a database connection issue, however I found a bug preventing errors from showing.
On line ~47 of library/wpos/config.php find the following line:

`$result['error'] .=  "ERROR: " . ": " . $errstr . " " . $errfile . " on line " . $errline . "\n";`

and place `die(json_encode($result));` after it.

You should then see a proper error when logging in.

Also, as you are using version 1.4.0, please refer to the latest apache config here:

https://github.com/micwallace/wallacepos/wiki/Apache-Configuration

**Comment by opensourceexpert** [comment]
Thanks again for the help here. After adding the above code I get this error now:

OKERROR: : require_once(/var/www/html/wallacepos/library/composer/autoload_real.php): failed to open stream: No such file or directory /var/www/html/wallacepos/library/autoload.php on line 5

**Comment by micwallace** [comment]
No worries. I think a composer rebuild is needed to add the correct autoload file.

In a terminal, go to the directory where you installed the files and run `composer install`.
You may need to install composer first.

**Comment by opensourceexpert** [comment]
Finally .... I am able to login as staff in POS termonal.
Many thanks to you Michael .

**Comment by micwallace** [comment]
No worries, I will add this to the installation guide once I finalise 1.4.0
