### ISSUE TITLE
Not able to setup on local windows machine

### ISSUE THREAD

**Issue by dclmetal87** [micwallace/wallacepos#66]
Hi, I have done all the setup requirements and got the installation wizard successfully, however, when I access via root http://localhost/ it says I need to setup a device and access first as admin, after filling with username: "admin" and the password I set in the instalation wizard then log in, I get the this through an alert window:

**"SyntaxError: Unexpected end of JSON input"**

and I cannot access the program at all, how can I correct this or what am I doing wrong?. Thanks in advance!!!

I am running windows 10.

**Comment by micwallace** [comment]
Please refer here for info on solving this issue:
https://github.com/micwallace/wallacepos/issues/65

Also note that WAMP is not fully supported.

**Comment by micwallace** [comment]
Did you end up getting it working?

**Comment by dclmetal87** [comment]
sorry I went on a family trip and I'm arriving. Actually I did get it to work I just needed to composer install on the directory where I copy the files to, I'm using windows 10, using xampp, apache 2.4 and php 5.6. However the live feed is not working, I don't know if it is port related or what but everything else does work. Thanks!!!

**Comment by micwallace** [comment]
Tips:
- Make sure you have apache mod_wstunnel installed and enabled.
- Make sure you are using the updated apache websocket proxy config as shown in README.md.
- Try running node or nodejs manually from the command line to see any errors:
  `node %installdir%/api/server.js` (command may be nodejs).

**Comment by alibinakhtar** [comment]
Hi,

I hope everyone is good, If anyone need assistance to install and configure it please let me know.

Ali

**Comment by guillermohaad** [comment]
hi  @alibinakhtar and @agustincl 
I want to install wallecepos on Windows. I try to do it but it shows me this message:

install:
http://localhost/wallacepos/installer/

message browser:
( ! ) Warning: require(C:/wamp64/www/library/wpos/AutoLoader.php): failed to open stream: No such file or directory in C:\wamp64\www\wallacepos\installer\index.php on line 28
