### ISSUE TITLE
Trying to deploy using dokku

### ISSUE THREAD

**Issue by epiqueras** [micwallace/wallacepos#67]
I have the dokku app and MySQL set up on my server. Everything goes smoothly until I do "git push dokku master". I get this error:

    Attempting pre-flight checks
    For more efficient zero downtime deployments, create a file CHECKS.
    See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
    CHECKS file not found in container: Running simple container check...
    -----> Waiting for 10 seconds ...
    remote: App container failed to start!!
    =====> myapp web container output:
    Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
    Recommending WEB_CONCURRENCY=1
    Launching nodejs
    boot.sh: 32: exec: /usr/sbin/apache2: not found
    Launching apache
    Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
    Recommending WEB_CONCURRENCY=1
    Launching nodejs
    boot.sh: 32: exec: /usr/sbin/apache2: not found
    Launching apache
    Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
    Recommending WEB_CONCURRENCY=1
    Launching nodejs
    boot.sh: 32: exec: /usr/sbin/apache2: not found
    Launching apache
    Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
    Recommending WEB_CONCURRENCY=1
    Launching nodejs
    boot.sh: 32: exec: /usr/sbin/apache2: not found
    Launching apache
    Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
    Recommending WEB_CONCURRENCY=1
    Launching nodejs
    boot.sh: 32: exec: /usr/sbin/apache2: not found
    Launching apache
    Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
    Recommending WEB_CONCURRENCY=1
    Launching nodejs
    boot.sh: 32: exec: /usr/sbin/apache2: not found
    Launching apache
    Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
    Recommending WEB_CONCURRENCY=1
    Launching nodejs
    boot.sh: 32: exec: /usr/sbin/apache2: not found
    Launching apache
    =====> end myapp web container output
    To dokku@myipaddress:myapp
    ! [remote rejected] master -> master (pre-receive hook declined)
    error: failed to push some refs to 'dokku@myipaddress:myapp'`

I've tried reinstalling apache2 but that didn't seem to do anything. Any clues on how I can solve this?

**Comment by micwallace** [comment]
Apologies mate I've just updated the dokku buildpacks and haven't had a chance to update the instructions. Apache and php are now installed via the dokku apt-get plugin rather than static binaries.
Once you install this it should work:

https://github.com/F4-Group/dokku-apt

**Comment by epiqueras** [comment]
Thanks! that fixed it.
But now I have a problem with the nginx.conf file.

    remote: nginx: [emerg] invalid number of arguments in "server_name" directive in
    /home/dokku/myapp/nginx.conf:9
    remote: nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by micwallace** [comment]
Are you using dokku with a domain?

If you post the nginx config I'll be able to better determine the problem.

**Comment by epiqueras** [comment]
No I'm just using the bare ip address.

**Comment by micwallace** [comment]
The nginx.conf.sigil template is specifically designed for using domains.
You'll need to edit it to work with ip:port.

**Comment by epiqueras** [comment]
I tried using the ip address instead of "{{ .NOSSL_SERVER_NAME }}"

    remote: nginx: [emerg] BIO_new_file("/home/dokku/tls/server.crt") failed (SSL:
    error:02001002:system library:fopen:No such file or
    directory:fopen('/home/dokku/tls/server.crt','r') error:2006D080:BIO routines:BIO_new_file:no such
    file)
    remote: nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by epiqueras** [comment]
I deleted it and let dokku generate one. It deployed successfully and gave me a url. I tried it in my browser and it didn't work.

**Comment by micwallace** [comment]
If you're not using ssl you will need to remove those lines. Check the logs and see if you can find anymore clues.

**Comment by epiqueras** [comment]
Getting a domain and using SSL fixed it.
