### ISSUE TITLE
Warning/Error stops install /installer

### ISSUE THREAD

**Issue by epiqueras** [micwallace/wallacepos#68]
I ran the installer and got this error that is stopping the installer:

    <br />
    <b>Warning</b>:  copy(/app/docs-template/templates/.config.json): failed to open stream: No
    such file or directory in <b>/app/library/wpos/models/DbUpdater.php</b> on line <b>94</b><br
    />
    <br />
    <b>Warning</b>:  require_once(/app/library/composer/autoload_real.php): failed to open stream:
    No such file or directory in <b>/app/library/autoload.php</b> on line <b>5</b><br />

**Comment by micwallace** [comment]
Ah seems I forgot to check that in, just added it:

https://github.com/micwallace/wallacepos/blob/master/docs-template/templates/.config.json

**Comment by epiqueras** [comment]
That fixed the first error but the second one is still there.

**Comment by developerfranso** [comment]
feel like the team made this errors deliberately

**Comment by micwallace** [comment]
Oh yeah I spent heaps of my spare time developing this just to give you a bad user experience lol.

You just need to regenerate composer config.
