### ISSUE TITLE
apache error log warning message

### ISSUE THREAD

**Issue by captainwasabi** [micwallace/wallacepos#7]
Got everything up and running.

Noticed the following warning in the apache error.log:

[Sat May 02 14:28:52.946893 2015] [proxy:warn] [pid 15457] [client 192.168.2.145:49641] AH01144: No protocol handler was valid for the URL /socket.io/1/. If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule., referer: https://pos/

**Comment by micwallace** [comment]
you may need to enable proxy_http as well as proxy_wstunnel.
Let me know if this is still an issue and I'll reopen it.
