### ISSUE TITLE
Base Price and Selling Price

### ISSUE THREAD

**Issue by madjapahit** [micwallace/wallacepos#71]
Hi, it would be good if while users adding / storing items to warehouse, WallacePos have Base Price and Selling Price.

This idea will extend WallacePos as a complete finance app.

Lets say i bought strawberry $10 USD as base price for 1 Qty, and then i can set $12 USD as selling price for 1 Qty, on sales (as staff) selling price will be main price for selling, so in dashboard we can see Revenue and Loss as one piece.

What do you think?

**Comment by micwallace** [comment]
https://github.com/micwallace/wallacepos/releases/tag/1.4.1
