### ISSUE TITLE
Unable to edit invoice template

### ISSUE THREAD

**Issue by lahiruchandima** [micwallace/wallacepos#73]
If user tried to customize the invoice template, invoice gets incorrectly printed.

The printed invoice does not contain the item names. The total sum is correct, but individual item prices are marked as 0 (item name is also not shown).

User does not actually have to do any significant change to the template to make this happen. Just opening the template editor and pressing save button without doing any change is sufficient.

If template is restored to default, problem gets fixed.

wallacepos is installed on XAMPP on Windows 7.

**Comment by micwallace** [comment]
https://github.com/micwallace/wallacepos/releases/tag/1.4.1

I've replaced the WYSIWYG editor with a code editor which should work a lot better.
