### ISSUE TITLE
Error: Not Found

### ISSUE THREAD

**Issue by SargonII** [micwallace/wallacepos#75]
Hi,

I've been trying to install your POS on a VPS running Ubuntu 16.04.
I've followed your documentation and once ready went to /installer.
The initial checks appeared to show all OK.

![wpos1](https://cloud.githubusercontent.com/assets/25673295/22804844/cc8167ce-ef12-11e6-9a4c-3c51b15093bd.PNG)

The database was configured and set up after I gave write permissions on /.dbconfig.json and I received no further errors.
I created an admin username and password but when I load /admin, I receive a pop up, with error: not found

![not found](https://cloud.githubusercontent.com/assets/25673295/22805066/b73cbd68-ef13-11e6-9cfe-8f21f230bb3b.PNG)

If I try to log in, the same error is generated.

I've checked and mod-rewrite is enabled, apache config is as below:

Looking at the console, it seems that "GET https://webpos....co.uk/api/hello?_=1486678265346 404 (Not Found)" is failing to load.

I think the issue may be similar to CaptainWasabi's - https://github.com/micwallace/wallacepos/issues/3
but I haven't been able to identify the cause.

Please can you point me in the right direction.

Thanks,

**Comment by solancer** [comment]
Even I'm affected by this. I'm trying to run this on my docker on my local mac machine.


![screen shot 2017-02-24 at 8 45 13 am](https://cloud.githubusercontent.com/assets/800668/23289103/9c46d3f8-fa6d-11e6-87ca-e405c8e78394.png)


![screen shot 2017-02-24 at 8 44 16 am](https://cloud.githubusercontent.com/assets/800668/23289087/86da90cc-fa6d-11e6-8e93-31228feb7152.png)
![screen shot 2017-02-24 at 8 44 09 am](https://cloud.githubusercontent.com/assets/800668/23289088/86dfff12-fa6d-11e6-999d-4db75157e8a5.png)

**Comment by micwallace** [comment]
You need to debug apache rewrites defined in the api/.htaccess.
Looking at the apache error log file is a good start.

**Comment by SargonII** [comment]
Thanks for the reply. I rewrote my config file for my virtual host using the details outlined in the readme file but still received the error.
Apache logs and error logs showed the GET attempt but no errors.
The .htaccess file didn't appear to be being read, to test I edited with garbage, to see if it threw a server error but there was nothing.
I checked my default apache config and saw that an allowoverride NONE was set on the main /var/www/ directory, I changed this to allow and this resolved the above issue.
I then received the SQLSTATE[42000] error but was able to resolve that as you have advised elsewhere.

The feed server shows as online, so all appears to be working. I'll test further tomorrow but this issue appears to be resolved.

Thanks,

**Comment by micwallace** [comment]
Thanks for the update, I'll add this as a note into the installation guide.

On 27 February 2017 11:26:38 AM AEDT, SargonII <notifications@github.com> wrote:
>Thanks for the reply. I rewrote my config file for my virtual host
>using the details outlined in the readme file but still received the
>error.
>Apache logs and error logs showed the GET attempt but no errors.
>The .htaccess file didn't appear to be being read, to test I edited
>with garbage, to see if it threw a server error but there was nothing.
>I checked my default apache config and saw that an allowoverride NONE
>was set on the main /var/www/ directory, I changed this to allow and
>this resolved the above issue.
>I then received the SQLSTATE[42000] error but was able to resolve that
>as you have advised elsewhere.
>
>The feed server shows as online, so all appears to be working. I'll
>test further tomorrow but this issue appears to be resolved.
>
>Thanks,
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/75#issuecomment-282601888

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SargonII** [comment]
OK, so I've ran into another issue, which I think I've identified but have so far been unable to resolve.
Again any help would be much appreciated.

The issue being that socket.io is not running successfully, generating the error - update feed could not be connected - on the realtime admin page.

![socket](https://cloud.githubusercontent.com/assets/25673295/23592551/af42b99c-01fa-11e7-9a95-b36c83a3ab3e.PNG)

I think this is due to @1.7.3 being installed when initially installed using (
    sudo apt-get update
    sudo apt-get install nodejs && apt-get install npm
    cd %/your_install_dir%/api
    sudo npm install socket.io) as in the readme.

NPM version is 3.5.2, apache version 2.4.18
I've tried removing the above socket.io version and then installing 0.9.17 but this completes with an error - @0.9.17 invalid. There is no error with 1.7.3 it re-installs without issue.

As I understand from a reference you posted - https://github.com/socketio/socket.io/issues/1696 - the issue is with @1.7.3 not playing nice with the proxy rules used. They suggest a way to resolve this by modifying the source code of socket.io-client/socket.io.js but I've not located this file.

What would you suggest?
Should it be possible to install 0.9.17 with the latest NPM and apache 2.4.18?

Thanks in advance.

**Comment by micwallace** [comment]
If you are using the current POS version then you will need the latest version of socket.io.

404 error in this case most likely means that you don't have the web socket proxy setup correctly.

**Comment by micwallace** [comment]
If you still can't work it out please open another issue using the issue template and post you apache virtual host config.
