### ISSUE TITLE
Updating inventory created new inventory

### ISSUE THREAD

**Issue by uzfarid** [micwallace/wallacepos#77]
Hi

When we click on inventory and edit and then click update without changing quantity then it will create a new row. Expectation is, when we click edit and then dont change anything , it should stay like before even if we click an update button

Is there any way to delete an inventory at all?

**Comment by micwallace** [comment]
This is expected operation, a stock history entry is created for every action. I would argue that this is helpful for determining if & when a stock-take has been performed for that item, even if the quantity has not changed. However if you feel strongly about it, feel free to submit a pull request with this operation as a setting.

There is no way to delete the inventory item except directly from the database.
