### ISSUE TITLE
When adding stock locations are duplicated in the listbox dropdown

### ISSUE THREAD

**Issue by captainwasabi** [micwallace/wallacepos#8]
Added a test item to Stored Items.
Add Stock

Expected: locations to be listed once.

Actual: Locations are duplicated in the drop down list

![image](https://cloud.githubusercontent.com/assets/8583375/7442312/72f30880-f0da-11e4-8683-1c17efd2611d.png)

**Comment by captainwasabi** [comment]
And when I went back to add another one to a different location it added 4 more:

![image](https://cloud.githubusercontent.com/assets/8583375/7442327/1e789b52-f0db-11e4-99c6-fecf9959e6a4.png)

**Comment by micwallace** [comment]
Will be fixed in the next version
