### ISSUE TITLE
Can't import: "Only CSV files less than 10mb can be imported."

### ISSUE THREAD

**Issue by sabre78** [micwallace/wallacepos#82]
[provide general introduction to the issue logging and why it is relevant to this repository]

## I exported "stored items" and then tried to import it back in. However I cannot eventhough the CSV file is only 4 kb. It gives me this error "Only CSV files less than 10mb can be imported."

[provide more detailed introduction to the issue itself and why it is relevant]

## I tried many times, but it is not letting me upload. After making a long csv, I expected it to work.

[ordered list the process to finding and recreating the issue, example below]

1. Exported "stored items", producing a 4 kb size .csv.
2. Dragged the csv produced from step 1 into the import space

## Expected result

So that the import module can work properly.

## Current result

The import module for "stored items" is not working properly, but saying "Only CSV files less than 10mb can be imported" everytime.

## `name of issue` screenshot
![error](https://cloud.githubusercontent.com/assets/19756007/24380909/eb53376a-130a-11e7-9cc2-f3247da7bca5.JPG)

**Comment by micwallace** [comment]
This is a misleading error that is being looked at and will be patched in the next version. It's actually to do with file type recognition rather than the file size.

Are you using Google chrome?

For the time being you can change the extension from .csv to .txt and it should work.

On 28 March 2017 9:32:23 AM AEDT, sabre78 <notifications@github.com> wrote:
>[provide general introduction to the issue logging and why it is
>relevant to this repository]
>
>## I exported "stored items" and then tried to import it back in.
>However I cannot eventhough the CSV file is only 4 kb. It gives me this
>error "Only CSV files less than 10mb can be imported."
>
>[provide more detailed introduction to the issue itself and why it is
>relevant]
>
>## I tried many times, but it is not letting me upload. After making a
>long csv, I expected it to work.
>
>[ordered list the process to finding and recreating the issue, example
>below]
>
>1. Exported "stored items", producing a 4 kb size .csv.
>2. Dragged the csv produced from step 1 into the import space
>
>## Expected result
>
>So that the import module can work properly.
>
>## Current result
>
>The import module for "stored items" is not working properly, but
>saying "Only CSV files less than 10mb can be imported" everytime.
>
>## `name of issue` screenshot
>![error](https://cloud.githubusercontent.com/assets/19756007/24380909/eb53376a-130a-11e7-9cc2-f3247da7bca5.JPG)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/82

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sabre78** [comment]
Ok. Thank you for the solution.

I was using firefox.

On 28-Mar-17 12:38 AM, micwallace wrote:
This is a misleading error that is being looked at and will be patched in the next version. It's actually to do with file type recognition rather than the file size.

Are you using Google chrome?

For the time being you can change the extension from .csv to .txt and it should work.

On 28 March 2017 9:32:23 AM AEDT, sabre78 <notifications@github.com><mailto:notifications@github.com> wrote:
>[provide general introduction to the issue logging and why it is
>relevant to this repository]
>
>## I exported "stored items" and then tried to import it back in.
>However I cannot eventhough the CSV file is only 4 kb. It gives me this
>error "Only CSV files less than 10mb can be imported."
>
>[provide more detailed introduction to the issue itself and why it is
>relevant]
>
>## I tried many times, but it is not letting me upload. After making a
>long csv, I expected it to work.
>
>[ordered list the process to finding and recreating the issue, example
>below]
>
>1. Exported "stored items", producing a 4 kb size .csv.
>2. Dragged the csv produced from step 1 into the import space
>
>## Expected result
>
>So that the import module can work properly.
>
>## Current result
>
>The import module for "stored items" is not working properly, but
>saying "Only CSV files less than 10mb can be imported" everytime.
>
>## `name of issue` screenshot
>![error](https://cloud.githubusercontent.com/assets/19756007/24380909/eb53376a-130a-11e7-9cc2-f3247da7bca5.JPG)
>
>
>--
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/82

--
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sabre78** [comment]
BTW, changing the extension to .txt still does not solve the problem.

**Comment by micwallace** [comment]
Thanks for the report, it's fixed in the latest commit:
8b469ab
