### ISSUE TITLE
Cannot order together item with modifier added along with item without the modifier

### ISSUE THREAD

**Issue by sabre78** [micwallace/wallacepos#83]
## I wanted to take an order of one qty of hot tea + milk (done with modifier) and one qty of hot tea without milk (The customers have different preferences). However, the till won't let me add hot tea without milk on top of hot tea+milk. Instead, it will just add 1 qty to the hot tea + milk, making it 2 qty.
The problem here is the pricing:
hot tea + milk = Rp10000
hot tea = Rp5000.

2qty of hot tea + milk is Rp20000
1qty of hot tea and 1qty of hot tea + milk is Rp15000
The price is expected to be Rp15000, but it is showing Rp20000 because of this problem.

## Process

1. I added hot tea, and changed the modifier to include milk as seen below:
![hot tea and milk](https://cloud.githubusercontent.com/assets/19756007/24392355/c92c7d68-1350-11e7-8a28-eed3b320c190.JPG)
2. Figure 2 below shows that 1 qty of hot tea+added milk is Rp10000 total (5000+5000)
![figure2](https://cloud.githubusercontent.com/assets/19756007/24392394/ed318f14-1350-11e7-9fb7-de036a8a1543.JPG)
3. In figure 2 above, I also added a stock search that is normally 1qty of hot tea without milk that is Rp5000. However, as can be seen in figure 3 below, it only make 2 qty of hot tea+milk, while it should be creating another item below that is without milk.
![figure3](https://cloud.githubusercontent.com/assets/19756007/24392531/8bfaac34-1351-11e7-8ecb-83827c4d350f.JPG)
The solution is supposed to be like figure4 below (I added a new item manually, which is not ideal since it will not be properly reported.):
![figure4](https://cloud.githubusercontent.com/assets/19756007/24392543/99bc1bdc-1351-11e7-8c71-eb13549e8533.JPG)

## Possible Fix

Create a new item after an item has a modifier on it.
OR even better, just make it as a new item every time we use the stock search or the category search on the right.

**Comment by micwallace** [comment]
Thanks, this will be fixed in the next patch.

**Comment by micwallace** [comment]
Thanks for the report, fixed in the latest commit:
8b469ab
