### ISSUE TITLE
Feature Request: Report - Item takings per location

### ISSUE THREAD

**Issue by sabre78** [micwallace/wallacepos#86]
I have 3 restaurants at different places. So I needed a good report from each location separately. For each location, I need these fields:
Item, Category for that item, Quantity Sold for that Item, Total $ sold for that item

Would it be possible to add this to the future fix?

**Comment by micwallace** [comment]
Nope sorry, I no longer have time to dedicate to this project but you can hire someone to do it for you.

**Comment by sabre78** [comment]
No worries, I'll find someone to do it. I'll send the files to you later for update.
