### ISSUE TITLE
Wallace Pos - Cyrillic problem in mysql database

### ISSUE THREAD

**Issue by ImarKelam** [micwallace/wallacepos#87]
## Context
I have an issue with the encoding in my mysql database.
When i add new item (product) in Wallace Pos Administration -> Items and the Name is written in Cyrillic everything in the browser look normal. Problem is that in the database this item is stored with strange unreadable name (example: Ð“Ñ€Ð°Ñ).

Current settings in db:
DEFAULT_CHARACTER_SET_NAME: UTF8
DEFAULT_COLLATION_NAME: UTF8_UNICODE_CI

How can I solve this problem?

![capture](https://cloud.githubusercontent.com/assets/15090820/24495417/bec5d9b6-153d-11e7-9963-36fe5257c667.JPG)

**Comment by micwallace** [comment]
http://stackoverflow.com/questions/4777900/how-to-display-utf-8-characters-in-phpmyadmin

You'll need to contribute to the project by working it out yourself ;-)
I'm no longer actively maintaining it.

**Comment by micwallace** [comment]
PS: Shows up OK in my installation of phpMyAdmin.

**Comment by ImarKelam** [comment]
After adding [ $this->_db->query("SET NAMES utf8"); ] in DbConfig.php in public function __construct the problem with Cyrillic encoding in database disappear.
