### ISSUE TITLE
I can't complete an order with status:Order

### ISSUE THREAD

**Issue by ImarKelam** [micwallace/wallacepos#88]
## Description:
After adding an order (with status: **Order**), then I can't complete this order (to status: **Completed**).

First I add one item and process the order.
Then I click on **Add Order** button. Now i have an order with status: **Order**
After that I'm trying to Complete this order. I'm clicking on button Complete but nothing happen.

## Steps with screens:
**_1st screen_**
![capture1](https://cloud.githubusercontent.com/assets/15090820/24658935/e61d36a2-1953-11e7-8020-1b423df5794a.JPG)
**_2nd screen_**
![capture2](https://cloud.githubusercontent.com/assets/15090820/24658936/e63f2aa0-1953-11e7-9f46-af06e60bd707.JPG)
**_3rd screen_**
![capture3](https://cloud.githubusercontent.com/assets/15090820/24658937/e64170b2-1953-11e7-8dbc-3df2a067c356.JPG)
**_4th screen_**
![capture4](https://cloud.githubusercontent.com/assets/15090820/24658939/e644e33c-1953-11e7-8111-7e3ac41ee3f8.JPG)
**_5th screen_**
![capture5](https://cloud.githubusercontent.com/assets/15090820/24658938/e6436ac0-1953-11e7-9058-ac8b892e49a4.JPG)

On last screenshot (5th) nothing happen when i click on the button Complete.

Could you test it?
Thanks!

**Comment by ImarKelam** [comment]
Any help?

**Comment by micwallace** [comment]
Thanks for the report, fixed in the latest commit:
8b469ab
