### ISSUE TITLE
Suggestion: Multiple Tax authorities per location

### ISSUE THREAD

**Issue by captainwasabi** [micwallace/wallacepos#9]
Ok, not sure what we will actually need, but I think I'll need support for multiple taxing authorities.  I.e. state sales tax and municipal sales tax.  IMO, there may be places that have federal, state, county, and municipality sales taxes.

**Comment by micwallace** [comment]
Hey,

I'd definitly be interested in expanding tax functionality but there not much I know about the US system.

Wow you guys can get taxed 3 times?!?

It would be great if you provide an overview of taxes in your area with some maths formulas.

I'm guessing that these taxes that you are mentioning are inclusive taxes, and are not added to the sale total?

At the moment, only one tax can be applied to an item, however it would definitly be possible to include multiple tax rates.

The one issue I can see is that item price exclusive tax rates may be needed?

Kind regards,
Michael

On 3 May 2015 5:01:25 AM AEST, captainwasabi <notifications@github.com> wrote:
>Ok, not sure what we will actually need, but I think I'll need support
>for multiple taxing authorities.  I.e. state sales tax and municipal
>sales tax.  IMO, there may be places that have federal, state, county,
>and municipality sales taxes.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/9

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by captainwasabi** [comment]
heh, more than 3 ;)  Cuz then there is state and federal income tax.  In the US they make the tax code so rediculously complicated that no one understands it so they can always come in and find something wrong.  I literally don't take every deduction I'm entitled to so that way if I get audited the govt will end up owing me money.  heh,

anyway, I think it's a 2d matrix of taxes.  The items will have a type (some things are taxed at different rates, like food) then for that type there can be a number of taxing authorities.  I wouldn't implement anything specific, just a general taxing system where the location determins the taxing authorities and the item-type determins the rate.  On one ticket you could have four different tax lines, state food, state goods, local food, local goods.  hmm, and maybe prepared food (like a cafe) is yet a different rate.  You could have a different register for each class, but you'd still have multiple rates from the different taxing authorities.

Yes, the tax is typically added to the "bottom line," not included in the price of each item.  Otherwize, for large chains that cover many locations, they would have LOTS of prices to keep track of.

**Comment by micwallace** [comment]
You'll be happy to know that the next version has a rule based tax system.
Probably about a month away, even sooner.
