### ISSUE TITLE
Translate ['REQUEST']

### ISSUE THREAD

**Issue by tomatoe45** [micwallace/wallacepos#90]
Hi.. your project is great.. that fits my needs.. however can you translate this with laravel?

**Comment by micwallace** [comment]
Translations would be a big job. Something I would like to do but currently don't have time.
Laravel is a php framwork, the POS does not use any framework.

Feel free to pay someone else to do it :-)

**Comment by tomatoe45** [comment]
hi @micwallace may i ask why the POS does not use any framework.?

**Comment by micwallace** [comment]
Flexibility

**Comment by tomatoe45** [comment]
I see.. thanks btw.
