### ISSUE TITLE
Hardware doubts

### ISSUE THREAD

**Issue by delpo** [micwallace/wallacepos#93]
I want to install WallacePOS for testing purposes and I just tried the live demo.  The idea is getting a cheap and useful PoS for different kind of small business. I have these questions:

**1) Where I can use the barcode scanner in the POS view (not admin)? I can't find how to scan products.**

**2) Which hardware do you recommend?** 

1. Barcode scanner

I found this, is it ok?

https://www.amazon.es/Excelvan-Esc%C3%A1ner-Port%C3%A1til-Sistema-Smartphone/dp/B019GILT4W/ref=sr_1_11?s=electronics&ie=UTF8&qid=1493076799&sr=1-11&keywords=escaner+codigo+barras

2. Printer

I found this, is it ok?

https://www.amazon.es/Excelvan-ZJ-Impresora-t%C3%A9rmica-compatible/dp/B00ZUD87U2/ref=pd_bxgy_229_3?_encoding=UTF8&psc=1&refRID=459DXQD40NERHE4DVBG1

If this printer you think it won't be ok, I suppose this will be fine:

https://www.amazon.es/Epson-TM-T20II-002-Terminal-Al%C3%A1mbrico/dp/B00KKT0M2C/ref=sr_1_3?ie=UTF8&qid=1493076513&sr=8-3&keywords=Terminal+de+punto+de+venta

3. Cash drawer

I found this, is it ok?

https://www.amazon.es/Approx-APPCASH01-Bandeja-efectivo-compartimentos/dp/B01BE7E1CA/ref=pd_sim_201_2?_encoding=UTF8&psc=1&refRID=QSEA2NZCCDKXK0HGN3AF

**3) Is there support for second screen? In order to show to the customer the products and the final amount of money to pay. I think it would be a good feature.**

I think this info will be useful for other people who want to start at PoS world. Thanks a lot!

**Comment by micwallace** [comment]
All scanners work as keyboard devices so any will work as long as you can connect it. Any 80mm thermal printer supporting ESCP should work. I bought a cheapie off ebay and it's worked pretty well for my purposes:
http://www.ebay.com.au/itm/EO80-High-Speed-POS-Thermal-Receipt-Printer-80mm-Auto-Cutter-USB-Ethernet-Serial-/150959730965?epid=1291557223&hash=item2325e6b115:g:PicAAOSwh6xTsqYc

But of course you can't go wrong with EPSON, they invented ESCP after all.

The cash draw must be connected via the printer.
