### ISSUE TITLE
Invalid SSL certificate in https://wallacepos.com

### ISSUE THREAD

**Issue by donnykurnia** [micwallace/wallacepos#94]
https://wallacepos.com is a landing and demo site for this app, but right now it had an invalid SSL certificate. When new user visit this site, modern browser will display error message.

The test result: https://www.ssllabs.com/ssltest/analyze.html?d=wallacepos.com

## Process

1. Visit https://wallacepos.com

## Expected result

The website displayed without errors.

## Current result

https://www.ssllabs.com/ssltest/analyze.html?d=wallacepos.com

## Possible Fix

Using a free SSL certificate from LetsEncrypt will solve this issue.

**Comment by jimktrains** [comment]
This is still an issue. The cert is not trusted.

**Comment by supertin** [comment]
It's using a StartSSL certificate. Most browsers have de-trusted them after a secretive sellout to a Chinese company in 2016.

If free is the only acceptable price, Let's Encrypt works fairly well (or so I believe).

**Comment by philipmcdonnell** [comment]
Looks like this has been corrected, should close this issue as fixed now...
