### ISSUE TITLE
Update feed offline - XMLHTTPRequest cannot load

### ISSUE THREAD

**Issue by dquapp** [micwallace/wallacepos#95]
Having issues getting my browser sessions to connect to socket.io, and thus are showing offline.

Am running on Windows 10 with WAMP64 and can verify that node.js is running and listening on port 8080.  I am going this on a local network and will not be using SSL.

My httpd-vhost.conf looks as follows:

Listen 8060
<VirtualHost *:8060>
         DocumentRoot c:/wamp64/www/pos
         ServerName 192.168.0.100

         <Directory c:/wamp64/www/pos>
            AllowOverride all
         </Directory>

         # WSPROXY CONF
         ProxyRequests Off
         ProxyPreserveHost On
         <Proxy *>
                 Order deny,allow
                 Allow from all
         </Proxy>
         RewriteEngine On
         RewriteCond %{HTTP:Connection} Upgrade [NC]
         RewriteRule /(.*) ws://localhost:8080/$1 [P,L]
         ProxyPass        /socket.io http://localhost:8080/socket.io/
         ProxyPassReverse /socket.io http://localhost:8080/socket.io/
         <Location /socket.io>
                 Order allow,deny
                 Allow from all
         </Location>
    </VirtualHost>

When launching the app in chrome debug tools I get a series of errors:

XMLHttpRequest cannot load http://192.168.0.100/socket.io/?EIO=3&transport=polling&t=Lm9pTvP. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.0.100:8060' is therefore not allowed access. The response had HTTP status code 404.

and
socket.io-1.4.5.js:1 GET http://192.168.0.100/socket.io/?EIO=3&transport=polling&t=LmA1Uw0 404 (Not Found)

Copy/Pasting in the the address and adding the port provides a valid response from the server.

Any suggestions?

Thanks.

**Comment by micwallace** [comment]
In https://github.com/micwallace/wallacepos/blob/master/assets/js/wpos/core.js#L1359

Change this line:
`var socketPath = window.location.protocol+'//'+window.location.hostname+(proxy==false ? ':'+port : '');`

To this:
`var socketPath = window.location.protocol+'//'+window.location.hostname+(proxy==false ? ':'+port : (window.location.port ? ':'+window.location.port : ''));`
