### ISSUE TITLE
Import Inventory?

### ISSUE THREAD

**Issue by MrByte** [micwallace/wallacepos#96]
Pardon if this is in the wrong place...

I have 2 questions, first are stored items tied to inventory by the stock code/name? 
Second, is there a way to import a large amount of inventory?  I see import for stored items.

Edit: Ok, answered 1 for myself. 2 is better said as "How can I easily import item quantities?" 

And Bonus 3, some way to correct inventory counts en masse after doing a physical inventory...

**Comment by micwallace** [comment]
Stock quantity levels are stored in a separate database table and linked to the item & location id, not the name or code. You could import using mySQL database, or if your not familiar with SQL, use phpmyadmin.
