### ISSUE TITLE
problem when print recipt with thermal bill printer

### ISSUE THREAD

**Issue by ravindug** [micwallace/wallacepos#99]
When I Print with thermal printer font is so small and don't use whole width of paper 58mm and print browser header and footer and that result long receipt at bottom browser footer saying "1of first page"

Anybody let me know how to avoid resulting long receipt print and enlarge fonts in receipt print.
thank you in advance.

**Comment by micwallace** [comment]
You need to use ESCP printing, please refer to the FAQ:
[https://wallacepos.com/faq](https://wallacepos.com/faq)

**Comment by ravindug** [comment]
Thank you for your reply and it worked and when I print receipt it's in disarray and I changed the CSS file in utilities to change font size to fit into the receipt but It Did not work too and I here attached a photo of the receipt too.
 you can see content is not proportionate 
![img_20170607_195506](https://user-images.githubusercontent.com/6562505/26884726-1758389c-4bbe-11e7-841e-db0008c2c473.jpg)

**Comment by micwallace** [comment]
Again, you need to need to use Webprint ESCP printing method for a thermal printing....browser printing usually won't work.

The templates you edited are used for bitmap mode but not text mode ESCP printing. If you continue experiencing problems please submit another issue using the issues template.
